### ISSUE TITLE
Project don't get pulls even when npm outdated show five updates

### ISSUE THREAD

**Issue by MindTooth** [dependabot/feedback#109]
Hi,

I'm not sure why this happens.  Is this because I have no `package-lock.json`?

This is the [`package.json`](https://github.com/srcery-colors/srcery/blob/master/package.json) in question.  It did in fact [submit some](https://github.com/srcery-colors/srcery/pulls?q=is%3Apr+is%3Aclosed), but I rejected the last one.  May there be a grumpy bot that don't like my any more?
I were unable to find any information that could give me an answer.

<img width="549" alt="screen shot 2018-07-26 at 13 19 30" src="https://user-images.githubusercontent.com/33870508/43259460-90e43932-90d6-11e8-9569-f97cc6985755.png">

**Comment by greysteil** [comment]
Ah, interesting - because you don't have a lockfile Dependabot is assuming that your application is a library. As such, it doesn't want to change the ranges in your `package.json` unless it has to.

Is there are reason you haven't committed a `package-lock.json`. The Dependabot logic could definitely be better here either way - I'll take a look at improving it.

**Comment by MindTooth** [comment]
As they are just build tools, I want the latest.  Having a `package-lock.json` doesn't fit with me.  I'm kind of a up-to-date fellow, and don't care about backward compatibility.

**Comment by MindTooth** [comment]
I'll close this for now.  Solved it as said before.  Thanks for the help 👍
