### ISSUE TITLE
Option for single pull request per update

### ISSUE THREAD

**Issue by zach-taylor** [dependabot/feedback#11]
We use deppbot (https://www.deppbot.com) at the moment and we like the idea of a single pull request for each update rather than a pull request for each gem update. The main reason we like this is we have a lot of dependencies, and it can get noisy and slow to perform a build for each one and the way our branch protections are set up.

Thanks for the consideration!

**Comment by greysteil** [comment]
Thanks Zach. We might add a setting for this at some point, but it's not on our roadmap right now - we prefer the multiple PRs approach as it makes them easier to test and merge. That said, we can see a world where we open a single PR for several dependency updates we know are backwards compatible.

In the meantime, Deppbot are the guys to use if you want a single PR with many updates in it.

**Comment by zach-taylor** [comment]
Sounds good 👍 I figured I would put it out there and explain our reasoning.

**Comment by greysteil** [comment]
Quick update: we'd still love to do this (group non-breaking updates), but it's going to need us to have lots of data to do it well (we need to know which changes are breaking). One for the future - don't worry, it won't fall off our roadmap.

**Comment by ad-m** [comment]
In my opinion it is not a problem that many changes will be under one pull request. Many CIs test each commit separately, so you can continue to accurately identify the defective dependency.

**Comment by elamperti** [comment]
+1 to this request. Having a weekly/monthly update of all my npm packages would allow me to check quickly if they break something. If that's the case, I can analyze it and fix it manually, but otherwise it's faster than the time and resource consuming alternative of bumping versions for each package. I want to focus on the code, not on updates, and one PR per package creates a lot of noise -at least in my small repos-.

**Comment by shusson** [comment]
@greysteil any news on this? I would like to be able to bump with one PR, if it breaks, bump with multiple PRs. The hope being that the original PR doesn't break often and thus we get the best of both flows.

**Comment by greysteil** [comment]
We're still a way off, but should get closer in the next few weeks. Basically, I need to do a lot of refactoring because the update process currently expects to be given a single dependency everywhere. That should happen pretty soon, since this isn't the only thing waiting on it. Once that's done, the changes to make this possible are a *lot* more straightforward.

In the meantime, I continue to recommend [Deppbot](https://deppbot.com) if you want a single PR with many Ruby updates in it 🙂 .

**Comment by styfle** [comment]
This was pretty painful for my Electron project to build the PR and then build the build `master` after merging. https://github.com/styfle/magnemite

I think the big problem is that after accepting 1 PR, all the other PRs need to be rebased and rebuilt again. So for 6 deps that need to be updated, you have to wait for 21 builds to complete. At 5 minutes per build, thats almost 2 hours. And you are spending that time clicking waiting and watching CI so you can click Merge on the next PR.

I did [fix a bug](https://github.com/styfle/react-server-example-tsx/pull/32) with travis-ci that was building the PR twice, once for the branch and once for the PR. But this is the default behavior so I'm probably not the only one with that configuration.

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#369
