### ISSUE TITLE
How to configure access to registry.npmjs.org

### ISSUE THREAD

**Issue by hauke-altmann-as** [dependabot/feedback#11]
Hi there when trying to scan a Javascript project, I get this error: 

> Dependabot couldn't authenticate with registry.npmjs.org.
> 
> You can provide authentication details in your Dependabot dashboard by clicking into the account menu (in the top right) and selecting 'Config variables'.

I then tried to create an access Token at npmjs.com and used that one with the Dependabot config variables for Javascript. However, the error stays the same and I don't have a clue what exactly fails. 

Is there documentation for this feature? Any hints?

**Comment by greysteil** [comment]
This one's probably easier to debug over email - can you ping me on support@dependabot.com with the name of the repo?

Assuming nothing buggy is happening, Dependabot would raise that issue if it tried to authenticate with npm to get a private package but the authentication failed.

**Comment by greysteil** [comment]
Digging into this on the most likely repo, it looks like this could be a combination of problems:
1. the token I think you entered was wrapped in quote characters. Dependabot ought to do a better job of stripping these
2. the token you entered doesn't appear to have access to the package in question, even once the quote characters are stripped
3. Dependabot could serve a better error message here by checking whether you already have auth credentials entered for a registry and saying they're invalid in a case like the above, rather than serving the same message as for absent credentials.

I'll take a look into 1) and 3) now. Can you take a look into 2)?

**Comment by greysteil** [comment]
FYI, 1) and 3) are now implemented. Can you let me know if you have any more trouble with 2)?

**Comment by hauke-altmann-as** [comment]
Thanks for the quick answer. I think the issue lies in the two affected projects, as they reference project dependencies that are private repositories and not published at all registry.npmjs.org. 

A clearer error message might help here. But after all, it's a problem with our project setup, not with dependabot.

The issue can be closed. Thanks for your help!

**Comment by greysteil** [comment]
👍 - feedback was still really helpful. We've now got a slightly nicer error message and some better validations 🙂
