### ISSUE TITLE
Fail with install_if in Gemfile

### ISSUE THREAD

**Issue by SuperSandro2000** [dependabot/feedback#114]
Dependabot fails with ``install_if`` in your Gemfile.
Example:
````
install_if -> { RUBY_PLATFORM =~ /mingw32/ } do
  gem 'win32console', '~> 1.3'
end
````
It would be quite convenient if Dependabot would understand that basic bundler code or just ignore it instead of failing.

**Comment by greysteil** [comment]
Thanks for the feedback, I’ll take a look.

**Comment by greysteil** [comment]
This was caused by Dependabot's sanitizing of `require_relative` (fixed [here](https://github.com/dependabot/dependabot-core/commit/fb1726e87226c32e0786f417bd2241199f252a3f)) and of `Canuby::Version` (fixed [here](https://github.com/dependabot/dependabot-core/commit/bbe8df4bb481e34664986e0ceae0b5f28091df5c)).

@SuperSandro2000 - in future please reconsidered your phrasing of lines like "basic bundler code". Your `canuby` project looks great by the way - good luck with it!

**Comment by SuperSandro2000** [comment]
Thanks for the fast fix!
This is my first gem so I am still learning. Switched to standard bundler code style a couple hours ago. I followed the basic rubygems.org guide and it didn't mention anything about that.
And thanks for the kind words. I have still a lot of work todo. It is planned that Canuby replaces this rather ugly project https://github.com/modorganizer2/modorganizer-umbrella

**Comment by SuperSandro2000** [comment]
Sorry for the spam but I just found this on your profile https://github.com/CocoaPods/Molinillo. The connections in life. Crazy. The old project was build with networkx and really over engineered. And I need to say this: great support!

**Comment by greysteil** [comment]
You're welcome! And yep, Molinillo is a great project. The algorithm is a little tricky to wrap your head around at first, but the `ARCHITECTURE.md` file in there does a good job of explaining what's going on.
