### ISSUE TITLE
Customize merge method

### ISSUE THREAD

**Issue by gsmendoza** [dependabot/feedback#117]
Hi Dependabot!

It would be nice if we can customize the merge method when automatically merging PRs. GitHub offers three merge methods:

1. Create a merge commit
2. Squash and merge
3. Rebase and merge

For our team, we prefer to use "Rebase and merge" since it makes commits easy to follow.

Thanks for the great app!

**Comment by greysteil** [comment]
Hey George,

Great suggestion, and you can do this from you account settings! If you select "settings" from the menu in the top right of your [dashboard](https://dependabot.com) then there's an option to have Dependabot not create merge commits.

I *think* squash and merge and rebase and merge are basically the same for Dependabot PRs, given that they're always a single commit, hence the two options rather than three. Let me know if I'm wrong, though!

**Comment by gsmendoza** [comment]
Thanks for the quick response @greysteil. I didn't expect to find the configuration there :)

Anyway, I've unchecked the option on our account. Will let you know if we have any more questions.

**Comment by greysteil** [comment]
Yeah, I really need to document where everything is / give the frontend and overhaul!
