### ISSUE TITLE
Why does dependabot remove patches from composer.lock [php]

### ISSUE THREAD

**Issue by tobybellwood** [dependabot/feedback#121]
Our project applies a number of patches (using cweagans/composer-patches)

When dependabot submits the PR, the composer.lock file has been stripped of the patches applied - is this a known behaviour?

e.g. can be observed in https://github.com/tobybellwood/govcms-composer-test/pull/2/files

**Comment by greysteil** [comment]
That doesn't sound good - I'll take a look into it.

**Comment by greysteil** [comment]
OK, I think I know what's going on here:
- `composer-patches` works by subscribing to some `composer` install events.
- it can only do this after it's been installed. As a result, most people place it high up in their `composer.json`
- Dependabot doesn't actually do the install locally, so never runs `composer-patches`

Fix on my side is simple: I'll just add `composer-patches` as a Dependabot dependency.

**I'd love your help** writing a test, however - what I need is a very small Composer package that has a patch I can apply. That way I can write a test that the applied patch doesn't get removed, and running it won't take forever. Could you put together a minimal case for me (that doesn't include a 5 minute Drupal install)?

**Comment by tobybellwood** [comment]
Cool - I'll work something out!

**Comment by tobybellwood** [comment]
I've knocked one up at https://github.com/tobybellwood/patch-test (it's got an old release, and a couple of patches to apply).

Confirmed that Dependabot sees the 1.0.5 update and scrubs patches from the PR https://github.com/tobybellwood/patch-test/pull/1/files

**Comment by greysteil** [comment]
OK, this should be fixed in [this commit](https://github.com/dependabot/dependabot-core/commit/cd57947dc3916cc7346f20ae4c2cf0e1d1ab8204). It's a little ugly (when I dug into it `composer-patches` was running scripts, which I can't allow on the Dependabot backend) but should do the job.

Can you look out for any accidental formatting changes to your `composer.lock` files in the next few PRs? I think I've got Dependabot set up to match the `composer.lock` format exactly, but if not I'll tweak things.

Thanks masses on the feedback on this one - it's how we keep making Dependabot better. 🙂

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#444
