### ISSUE TITLE
Automerge questions

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#136]
I've been playing around in a dummy repo to try to see how Dependabot's automerging works. I set up the repo in Dependabot to automerge everything (and don't have any business-hours-only limitation set up), and yet I haven't actually seen any of Dependabot's PRs merge automatically.

- First I had Dependabot create [this PR](https://github.com/panorama-ed/dummy-repo/pull/4)
  - At this time the repo's branch permissions had:
    - code review approval required
    - only users in a particular GitHub organization can push to `master` (I wanted to test whether this would impact Dependabot or not)
  - Dependabot created the PR but did not merge it or comment that it could not merge it (as you mentioned [here](https://github.com/dependabot/feedback/issues/130#issuecomment-411337599)).
  - I approved the PR and Dependabot still did not merge it.
  - I lifted the branch restriction to allow anyone to push to `master` and Dependabot still did not merge it.
  - I bumped the repo in Dependabot's settings and Dependabot still did not merge it.
- Next I tried having Dependabot create [this PR](https://github.com/panorama-ed/dummy-repo/pull/5)
  - At this time the repo's branch permissions had:
    - only users in a particular GitHub organization can push to `master` (I wanted to test whether this would impact Dependabot or not)
  - Dependabot created the PR but did not merge it or comment that it could not merge it (as you mentioned [here](https://github.com/dependabot/feedback/issues/130#issuecomment-411337599)).
  - I lifted the branch restriction to allow anyone to push to `master` and Dependabot still did not merge it.
  - I bumped the repo in Dependabot's settings and Dependabot still did not merge it.
- Finally I tried having Dependabot create [this PR](https://github.com/panorama-ed/dummy-repo/pull/6)
  - At this time the repo's branch permissions had no limitations.
  - Dependabot created the PR but did not merge it or comment that it could not merge it (as you mentioned [here](https://github.com/dependabot/feedback/issues/130#issuecomment-411337599)).
  - I bumped the repo in Dependabot's settings and Dependabot still did not merge it.

I'm not sure why Dependabot hasn't merged any of these... is it because there are no tests for the repo? If so, and if there were tests, what would the expected behavior for each of these three scenarios be (approval and branch permissions, branch permissions, no limitations)?

Thanks!

**Comment by greysteil** [comment]
Hey Jacob,

Thanks for giving Dependabot a try, and for getting in touch.

You're right - the reason Dependabot hasn't automerged any of those is because there's no CI on them. Here's what would have happened if there were CI:
- In the first case, assuming CI passed, Dependabot would attempt to automerge but fail (because of the approval requirement and restriction on pushing to master). As a result, it would comment on the PR saying it was unable to merge and would disable automerging (so as not to spam you with comments)
- In the second case you'd get the same result. Sadly there's no way to specify that Dependabot is one of the users allowed to push to master (there's a long running request for GitHub to fix this [here](https://platform.github.community/t/repositories-which-have-protected-branches-with-push-restrictions-have-no-ability-to-grant-push-rights-to-integrations/1376/53))
- In the final case, Dependabot would wait until your tests had run, then check whether the PR was mergeable and merge it if it was.

Hope that helps clear things up. I *think* the above is the best flow Dependabot can manage, given the permissions issue with GitHub, but if you have other ideas please do let me know.

**Comment by JacobEvelyn** [comment]
Great, thanks for all the info @greysteil !
