### ISSUE TITLE
Allow ruby projects without a Gemfile.lock

### ISSUE THREAD

**Issue by NullVoxPopuli** [dependabot/feedback#14]
I'd like to use this on a couple of my gems:

https://github.com/NullVoxPopuli/drawers
https://github.com/NullVoxPopuli/skinny_controllers/

and it's recommended? to not use a Gemfile.lock on gems? 
So, I'm not sure how'd you'd know what to upgrade to / from.
I guess maybe if we could set up some sort of auto-building? idk, maybe that's another kind of service or something

**Comment by greysteil** [comment]
Hey @NullVoxPopuli.

Hmmm, this is a tricky one. What's the effect would you want Dependabot to have when running on your gems?

We've steered clear of supporting Ruby libraries because, generally speaking, you want to keep the requirements in the `gemspec` as relaxed as possible, rather than updating them all the time. (I can see that on both of your gems they're fully relaxed already.) That's very different to the goal with Ruby applications, where you want to keep the `Gemfile.lock` as up-to-date as possible.

**Comment by NullVoxPopuli** [comment]
I'm not 100% sure, but I've been caught a few times by dependencies updating past a major version or whatever, and then _that_ breaks the build.

The only thing I can think of would be to have some sort of metadata file that has a list of dependencies that are tested against.

But that may be outside the scope of dependabot? idk. maybe feature request?

**Comment by greysteil** [comment]
Cool, I'll have a think about that - can see it would be a useful service for maintainers to know if a new version is released that breaks compatibility. Might need to be a separate app to Dependabot.

In the meantime, I've updated the error that Dependabot will serve if you attempt to use it on a gem to be:

> Dependabot is designed for applications, and doesn't support Ruby libraries as their dependency management needs are very different.

Resolving this in the hope that the above is clear enough, but let me know if you think we could do better. Thanks for the feedback!

**Comment by tf** [comment]
Just to add another point of view, even though the issue has already been closed: Open ended gem dependency requirements are at least controversial. In fact, `gem build` even prints a warning:

> WARNING:  open-ended dependency on rspec (>= 3.0.0, development) is not recommended

In his [great article on the topic](https://blog.codeship.com/optimists-guide-pessimistic-library-versioning/), Richard Schneemann points out:

> The >= versioning strategy requires the least amount of effort from a maintainer. Since maintaining a gem is already really hard, it’s what most people use. The downside is that if you’re using version 0.0.1 of Wicked with a Rails 5 app, it won’t work. However, you’ll still be allowed to install it and try it. This will waste the end user’s time.
> 
> Unfortunately, you can’t retroactively add dependency versions to gems. We can’t go back in time and say, “Hey, Wicked 0.0.1 shouldn’t be used with Rails 5.” Released library versions are immutable; if you changed part of your library including the dependencies, it would no longer be the same version.

We therefore try to use pessimistic versioning in our gems, making explicit which major versions the gem supports.

    s.add_runtime_dependency 'some-gem', [>= 1.3, < 3]

It would be awesome if Dependabot could open PRs on our project to update the range to `[>= 1.3, < 4]` once that's released. After seeing the test suite pass (and possibly some additional manual verification) the maintainer could merge the PR.

**Comment by NullVoxPopuli** [comment]
Interesting, I'd be a fan of that. Dependabot could even suggest those additions to the gemspec, by looking up the recent gem version and add in a pr `, ['~> X.0']`
And then dependabot would only need to check the major versions (if ~> is used)

**Comment by greysteil** [comment]
I'd be totally up for supporting that flow @tf. I think we'd need to add it as an entirely new flow (called `bundler-lib` or something like that) in much the same way as adding support for a new language works (see [this PR](https://github.com/dependabot/dependabot-core/pull/24) for example).

**Comment by greysteil** [comment]
OK, I've got something working. I haven't put it in the front-end yet because it's still a little raw, and because I'm not 100% sure how it should interact with bumping for applications (there's the unusual case where a repo has a Gemfile.lock, and Gemfile, AND a gemspec).

@NullVoxPopuli would you be up for trialling it on [drawers](https://github.com/NullVoxPopuli/drawers) / [skinny_controllers](https://github.com/NullVoxPopuli/skinny_controllers)? I'll set it up for you if so.

**Comment by NullVoxPopuli** [comment]
Of course! Sounds awesome!

**Comment by greysteil** [comment]
OK, you're set up. Unfortunately the specifications in your gemspecs for those gems are totally open-ended, and since I haven't added an ability for Dependabot to automatically update you to pessimistic versioning there's no work for it to do on them! 🤦‍♂️

**Comment by greysteil** [comment]
@tf - could I persuade you to give it a whirl, too? No front-end, but I can add any repos you want from console (and you can disable / edit them from the frontend once they're in).

**Comment by tf** [comment]
@greysteil wow, you people are fast! I've granted Dependabot permissions for two test repositories:

https://github.com/tf/pageflow-dependabot-test
https://github.com/tf/pageflow-panorama-dependabot-test

The first one contains a bunch of outdated dependencies:

* Major version updates (i.e. `cancancan ~> 1.10` where `2.0` is available) 
* Minor version updates (i.e. `device-async ~> 0.9.0` where `0.10` is available)

The second repository depends on the first. I've downgraded the gemspec to depend on `pageflow ~> 0.11`, so Dependabot can suggest the update to `12.0` (we shifted the dot and skipped 1.0). This is the main use case I see for us in the future.

**Comment by greysteil** [comment]
Awesome - I've run it on both (and found a bug, which I've fixed). Let me know if the results are what you'd expect / want.

**Comment by tf** [comment]
The results look really promising. Some first thoughts:

It's great that Dependabot knows how to extend ranges: Going from `~> 2.3`, to `>= 2.3, < 4` it's important to stay compatible with `2.3`. Will it also work if the original gemspec already contained a range (i.e. going from `>= 2.3, < 4` to `>= 2.3, < 5`)? I tried looking at the PR but could not really pin it down.

Looking at the generated PRs, I realize that the value proposition of Dependabot in the context of gems is very different from applications. While in application probably most PRs are really lightweight and immediately actionable (i.e. "Hey use Devise 2.4 instead of 2.3), in a gem I basically see two situations:

* We depend on a major version of a gem (i.e. `~> 4.2` or `>= 3.1, < 5`). When 5.0 comes out, Dependabot can suggest the major version update. We get a nice reminder to stay up to date. If our tests still pass, there is a good chance the breaking change does not affect us (i.e. drop Ruby 1.9 etc),

* We already depend on an older version than the latest release or a more specific version (i.e. '~> 4.2.0' since we already know that `4.3.0` contains some detail that require us to some work - semver is not always perfect). When 4.4 comes out, the generated PR is still a nice reminder. But the fact that we already nailed things down a bit more in our gemspec is an indication that the PR will probably be less actionable.

I'm not really finished thinking about what this means, though.

**Comment by NullVoxPopuli** [comment]
@greysteil I've updated both my gems to have version ranges on both drawers and skinny_controllers. Thanks!

**Comment by greysteil** [comment]
It'll handle cases where you've already got a range - the relevant code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/update_checkers/ruby/gemspec.rb#L19-L32) and it basically just loops through each of your requirements, looking for ones it needs to update.

I'm still not 100% sure of the value proposition here. I think it can be useful, but it needs to be positioned just right. For a start I think the PR text needs some work to position PRs like these ones as helpful reminders / places to start, rather than the finished article.

**Comment by greysteil** [comment]
And thanks for trying it, guys!

**Comment by tf** [comment]
I think the main thing to avoid is noise. If I just don't have the time to update to Rails 5, being reminded each time a new Rails patch level version is released might be annoying.

**Comment by greysteil** [comment]
Agreed. For libraries, that's already sorted as long as the specified you use isn't `==` (seems unlikely) - Dependabot will only update you when a *different* change in the requirements would be necessary to permit the latest version.

For apps it's a bit trickier - we've had other people say that they *want* to be updated for the next patch release, because they're waiting for a bug fix in it.

We could try doing something clever with specifiers, or adding settings to within the app itself, but I'd like to keep the interface on it as tiny as possible, and ideally operated entirely through GitHub comments.

**Comment by tf** [comment]
Maybe there could be a way to tell Dependabot that we are not planning to support a new version by closing the PR and adding a `wontfix` label. Or even better, allow to reply to Dependabot in the PR with something like "Planned for v4.0", which would make Dependabot wait until there is a v4.0 milestone or something like that.

One further tiny nitpick that might be worth considering: If we are using `some-gem ~> 4.3` and then `5.0` and `6.0` are released, Dependabot will suggest updating the range to `=> 4.3, < 7.0`. Still fixing the tests in the PR alone will only prove compatibility with `6.0` - not `5.0`. This might be something the maintainers have to watch out for themselves, though.

**Comment by greysteil** [comment]
`wontfix` label is a nice idea. Definitely a separate issue though 😉 .

For libraries, however, I've just got everything working how I want it, and it's live in the main app - you can add a library in the same way you would any other Ruby project, and Dependabot will just do the right thing. 🔥

**Comment by NullVoxPopuli** [comment]
woo!!! great work!
