### ISSUE TITLE
Dependabot doesn't recognoze multiple commands in a single comment

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#142]
I tried to teach Dependabot about default labels and assignes. I put 2 commands to a single comment, but a bot recognized only the first one.

Here is a comment: https://github.com/php-coder/mystamps/pull/936#issuecomment-413540182
Here is a PR that was created after that comment: https://github.com/php-coder/mystamps/pull/941 (it isn't assigned to me)

**Comment by greysteil** [comment]
I happened to look through the PRs and noticed that.

This is a tricky one. The regexes on my side for picking up commands are as conservative as possible, to avoid Dependabot accidentally picking things up when it shouldn't do.

In this case, however, I think it's super clear what the intention was because you've put a linebreak in. I'll have a look at getting Dependabot to pick up multiple commands in a single comment in that case.

**Comment by greysteil** [comment]
Change is deploying now. 🍸
