### ISSUE TITLE
Links to pull requests in changelog linking to local repo instead of dependency

### ISSUE THREAD

**Issue by StefanWallin** [dependabot/feedback#144]
When updating the activerecord-import gem I noticed that they, [in their changelog](https://github.com/zdennis/activerecord-import/blob/master/CHANGELOG.md) have scribbled PR-references without links such as `#527`. These would link to our inspected repo instead of the dependencies repo(probably because of github autolinking). 

Could we maybe change this to function like the commit reference logs where you utilise the `https://github-redirect.dependabot.com`-domain or maybe just insert a link directly with the markdown syntax?

**Comment by greysteil** [comment]
Good catch! Fixed in https://github.com/dependabot/dependabot-core/commit/ac4eddb28937692effc14961681fc2353c792ff4.

The issue here was that `activerecord-import` was attempting to backslash-escape its issue references (which GitHub ignores, so Dependabot still needs to sanitize).

Thanks for flagging this one!
