### ISSUE TITLE
Q: how to edit bot commits?

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#148]
I'd like to include links to the changelogs in commit messages. How I can do that? (And these links not the same as bot includes in PR.)

**Comment by greysteil** [comment]
Dependabot should already be including those, if it can find them. The relevant code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/message_builder.rb#L54-L60).

Is there an example PR it should have got a changelog for?

**Comment by php-coder** [comment]
> Is there an example PR it should have got a changelog for?

There are plenty of them:
* https://github.com/php-coder/mystamps/pull/946
* https://github.com/php-coder/mystamps/pull/936 (this plugin lives together with surefire plugin -- https://github.com/apache/maven-surefire)
* https://github.com/php-coder/mystamps/pull/942
* https://github.com/php-coder/mystamps/pull/943
* https://github.com/php-coder/mystamps/pull/938

**Comment by greysteil** [comment]
OK, I reckon I've got a way for Dependabot to find links to the repos for `togglz`, `maven-failsafe-plugin` and `liquibase`. `commons-lang3` is harder, because the GitHub repo for it is a mirror and isn't mentioned anywhere in the POM, and it looks like Dependabot *did* find the repo for `groovy-all`, it's just that there wasn't a changelog there (unless it's looking in the wrong place?).

Will get the change I'm thinking of implemented tomorrow morning.

**Comment by greysteil** [comment]
OK, I've just deployed https://github.com/dependabot/dependabot-core/commit/1c404423a93646a5483d47319ceb78aa9e1ab338, which should improve things here. It won't be perfect, but finding changelogs is something of a whack-a-mole issue!

If you see others that Dependabot has missed / could do better one, please do tag me in the PR (you can just mention @dependabot to do so).
