### ISSUE TITLE
Feature request: Ignore dependencies using code comments

### ISSUE THREAD

**Issue by sloria** [dependabot/feedback#150]
It would be great if dependencies could be conditionally ignored using a code comment.

Something like:

```bash
flask  # dependabot: ignore
Django # dependabot: >=1.8,<1.9
```

Related to #72 
See pyup: https://pyup.io/docs/bot/filter/

**Comment by greysteil** [comment]
Oh man, sorry I never replied to this.

This is tricky for Dependabot because we deal with so many different file types. What works for `requirements.txt` wouldn't work for a `Pipfile`, etc.

We're about to overhaul our dashboards and add a show view for repositories, from which you'll be able to specify ignores. Hopefully that will alleviate this problem (and of course there's already `@dependabot ignore this dependency`), but I can see how code comments is a useful additional control. We'll reconsider doing that (and defining a format for them on all files) once the dashboard work is done (but no promises on it - sorry!).

**Comment by greysteil** [comment]
We've just shipped support for config files, which can include a list of `ignored_updates` - that should give you exactly what you need here 🙂 

https://dependabot.com/blog/introducing-config-files/
