### ISSUE TITLE
.NET alternative nuget feeds

### ISSUE THREAD

**Issue by josesimoes** [dependabot/feedback#171]
I'm guessing that dependabot relies on nuget.org feed to determine if there are new versions of the package. 
It's common to use other Nuget feeds, specially for development, like https://www.myget.org

The settings for a repo should allow choosing/enter alternative nuget feeds to use on the checking.

**Comment by greysteil** [comment]
We'll automatically pick up these up if you have them in a `nuget.config` file, or if you enter them as repositories in the `Config variables` section of your Dependabot dashboard. Is there anywhere else we should be picking them up from?

**Comment by josesimoes** [comment]
That's is quite all right! ✔️ 

I totally missed that option... 


Just a couple of comments on the config vars for a .NET "repo" :
- I believe the name is "Nuget feed" is more common and widely use than .NET repository
- For public feeds there is no need to enter a credential, right now, the dialog requires this in order to continue. I would suggest that this is made clear in the field comments there, that for public feed this could be left blank, for feeds requiring use/pass of access token, bla, bla, bla. And, of course, accepting the empty field! 😉 

Again: you guys did an awesome job with this! I'm loving it.

**Comment by greysteil** [comment]
Awesome. I've done the rename - very useful feedback!

One repos without credentials, what's your thinking on adding them as config variables rather than specifying them in a `nuget.config`? How are they specified on your local machine / servers? If that's not in a `nuget.config` then it seems pretty clear Dependabot will need to support specifying them without credentials, but are there other things to consider (like should a specified repo replace the main Nuget feed, or augment it)?

**Comment by greysteil** [comment]
👌 - will report back when it’s done

**Comment by josesimoes** [comment]
Forgot to answer about the last bit: when several feeds exists, none is supposed to replace the other. The listing from each of them are "combined" and the highest version is found, then processed from whatever source where it is.

**Comment by greysteil** [comment]
Done! You can now add NuGet feeds without a token. Thanks again for the feedback and advice!
