### ISSUE TITLE
Show directory path on the website

### ISSUE THREAD

**Issue by simondel** [dependabot/feedback#18]
When a language has been configured using a directory path, it would be nice to be able to see it (instead of having to hover over the `i` sign).

Since there is plenty of whitespace, I don't think space would be an issue:
![image](https://user-images.githubusercontent.com/4221997/40040832-1dd67bdc-581c-11e8-9060-ad58eea59b39.png)

**Comment by greysteil** [comment]
That looks really non-ideal!

I *think* a better solution would be for me to finish up adding Lerna support, so that all of the above could be combined into a single update config. That would mean getting a single PR to bump a version in all of your packages, though - would that work? If not I'll have a think about a nicer way to show diretory.

**Comment by simondel** [comment]
Sounds good!

**Comment by greysteil** [comment]
@simondel - Lerna support is now live. Should mean you can delete all of the update configs for stryker except the base one. 🎉
