### ISSUE TITLE
Custom specification of PR titles

### ISSUE THREAD

**Issue by dwaynebailey** [dependabot/feedback#186]
It would be great to control the content of the PR title.  I know labels is probably a better approach but we have some pipeline steps that look at strings in the title to determine if it should build a test deployment.  Would be useful to always build test deployments for depdendabot PRs.

**Comment by greysteil** [comment]
Thanks for the request @dwaynebailey.

We've been cautious about this one because Dependabot's PR title logic isn't totally trivial - you can see the code [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/message_builder.rb#L45-L49). As a result, full customisation could be quite complicated for users.

Do you have access to anything else in your pipeline steps? Labels are an obvious one, but Dependabot also creates all of its PRs using the @dependabot-bot account, signs-off the commit messages, prefixes its branches with `dependabot/` and includes a `Dependabot commands and options` section in the PR message. Could you use any of those to identify Dependabot PRs?

**Comment by dwaynebailey** [comment]
@greysteil the most likely candidate I started to explore is indeed labels and I'll look at that.  Currently users prefix PRs with `[PREVIEW]` if they need a preview build.  They could potentially do the same with labels, if I can change the pipeline.

**Comment by Kocal** [comment]
This would be really nice to have this kind of feature.

For my own case, I'm maintaining an app (a CLI tool for our projects at work) by updating dependencies through Dependabot pull requests.

I'm using [semantic-release](https://github.com/semantic-release/semantic-release) for automatic releases, but sometimes it doesn't release anything because every commits (squashed dependabot pull requests) between master and the last version is a `chore` commit.

To force a new release when I only updated dependencies, I have to rename commit message `chore(deps): ...` to `feat(deps): ...`, but this is not really ideal. :confused: 

Something like `@dependabot use git-commit-type <type>` - or through UI - would be great! :smile:

**Comment by guitarrapc** [comment]
I've also using [semantic-release](https://github.com/semantic-release/semantic-release) and merging pull request by change dependabot's PR title. It would be nice if I can set to insert `Prefix` of the PR title.

**Comment by bennyn** [comment]
@greysteil We saw that Dependabot changed the prefixes from being `build(deps)` & `build(deps-dev)` to `chore(deps)` & `chore(deps-dev)`. At Wire we have some automation in place which checks for the commit prefix to determine if a version should be build or not. When a prefix changes then this can confuse our build logic. Is it possible to have the prefix customizable? Would be great if it could be user-defined in the "Project Settings" on https://app.dependabot.com/.

**Comment by bennyn** [comment]
> Can you point me to the PR / repo where this changed?

Here you can see the Dependabot PRs to update the `styled-components` package:
- October, 31st it used **build(deps)**: https://github.com/wireapp/wire-web-packages/pull/1271
- November, 29th it used **chore(deps)**: https://github.com/wireapp/wire-web-packages/pull/1345

I think it would be great to have it user-defined so you can choose to use "build" or "chore" or something else.

**Comment by greysteil** [comment]
OK, I'm shipping https://github.com/dependabot/dependabot-core/commit/694dfe841fb20c03e806fbf33db57dcf626d4a7b how which should help with this. It means that if you edit the commit message on the most recent Dependabot PR then Dependabot will fall in line and use that. Not perfect if you have multiple Dependabot PRs open (it's always going to pick up the most recent Dependabot commit), but hopefully not bad.

Next week (hopefully) we're going to ship config files, at which point I think making the prefix configurable makes sense.

**Comment by greysteil** [comment]
Everyone on this thread: I'd love your feedback on https://github.com/dependabot/dependabot-core/pull/1227, which will make the PR (and commit) prefix configurable. Will it give you what you need?

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/pull/1227.
