### ISSUE TITLE
Seeing different github authors, messing with our CI

### ISSUE THREAD

**Issue by lucas-nelson** [dependabot/feedback#191]
I'm seeing some commits authored by `dependabot[bot]` and some authored by `dependabot-bot`. It's hard to tell, but we think the first is associated with the email address `dependabot[bot]@users.noreply.github.com` and the latter with email `support@dependabot.com`.

If I link through from a commit on the author name in github the URL is either:

* `https://github.com/org/repo/commits?author=dependabot%5Bbot%5D`
* `https://github.com/org/repo/commits?author=dependabot-bot`

This messes with our CI setup in Buildkite. We've now asked BK to add the second email (c.f. https://github.com/buildkite/feedback/issues/313). Is there a list of possible dependabot commit emails available?

**Comment by greysteil** [comment]
Hey @lucas-nelson,

It's just those two auth names you'll ever see from Dependabot, and just those two email addresses (the noreply one is a GitHub bug that we're hoping they'll fix).

Long story short, it's not possible for the `dependabot[bot]` user to sign commits and have them show up as verified on GitHub, because GitHub doesn't allow us to upload a public key for it. To get around that we use the `dependabot-bot` account as the author on commits.

Apologies for the extra work, and for the bad email address showing up.
