### ISSUE TITLE
add a "force" or "redo" command?

### ISSUE THREAD

**Issue by Pomax** [dependabot/feedback#196]
Sometimes someone new to dependabot PRs will update a file in its commit, without a way to undo that, so dependabot will go "sorry, someone else edited my files, I can't rebase anymore now" even though we don't care about whether or not it "can", just that it "does" =)

Would it be possible to add a new command like `@dependabot force-rebase` or `@dependabot redo`, to make it throw away any changes past its own and _only_ redoing the dependency bump based on whatever master is right now?

**Comment by greysteil** [comment]
That's a really good suggestion. I'll try to get it added today.

**Comment by greysteil** [comment]
Took a little longer than I though but I've just shipped this as `@dependabot recreate` (I couldn't think of a perfect name for it, as recreate suggests that Dependabot would close the PR and open a new one, but I think that's closest to what's happening. If folks get confused I may change it so that it actually *does* close the PR and open a new one).

Thanks for the feedback!
