### ISSUE TITLE
Bumping one gem bumps another

### ISSUE THREAD

**Issue by biow0lf** [dependabot/feedback#21]
Example: https://github.com/biow0lf/evemonk/pull/201

**Comment by greysteil** [comment]
Hey @biow0lf, thanks for the feedback!

Do you have a strong view on what Dependabot should do here?

At the moment, Dependabot is following normal `bundle update lograge` behaviour, which is to update the dependency's sub-dependencies (and the sub-dependencies of its sub-dependencies, etc.) to the latest version. Since none of those sub-dependencies are listed in your `Gemfile` we assume you don't want to hear about them in the PR, and trust that `lograge` etc., specify their sub-dependency requirements accurately in the `gemspec` files (so everything still works).

**Comment by greysteil** [comment]
Closing as this is the standard `bundle update` behaviour. Other suggestions always welcome, though - no reason we shouldn't strive to improve Bundler!
