### ISSUE TITLE
"@dependabot merge" merged before CI passed

### ISSUE THREAD

**Issue by danpalmer** [dependabot/feedback#212]
The documentation for the command says:

`@dependabot merge will merge this PR after your CI passes on it`

It actually just merged a PR before CI had passed on it. Thankfully we did this on a low impact repo, but we do continuous deployment on other repos and this could have been fairly bad there.

**Comment by greysteil** [comment]
Oh wow, that is not cool - can you ping the URL for the PR to support@dependabot.com? I'll be able to look in our logs to see what's happend.

**Comment by greysteil** [comment]
My guess is that you *might* have said the command before your CI kicked off? If you say `@dependabot merge` on a PR when there is no CI then Dependabot will merge it straight away, and if none of your CI providers have notified GitHub that they're working on the PR then there's no way for Dependabot to tell that it should expect CI to run at some point.

**Comment by greysteil** [comment]
FYI, that automerging functionality (e.g., automerge patch releases) doesn't behave in that way - it just refuses to merge full-stop unless your repo has CI on it.

**Comment by danpalmer** [comment]
The PR was https://github.com/thread/thread-ios/pull/75

> My guess is that you might have said the command before your CI kicked off?

This was my guess too. I suspect it might have happened, but I think that's still a bug. I don't really think about my PRs as having an "unknown CI" state as all our PRs are run through CI and we don't merge without it. I'm not sure what the solution is, but it feels dangerous at the moment.

Not sure what happened, but would be great to get it fixed.

**Comment by greysteil** [comment]
Sounds like the best solution here is for Dependabot to do better detection of whether you're using CI or not - if you're not then the way Dependabot behaved on this PR is correct, but if you are and your CI provider is playing up (taking a long time to send a notice to GitHub saying that it's running) then I agree this is a bug.

I'll have a think about exactly how we do that and try to get something implemented this evening / tomorrow.

**Comment by danpalmer** [comment]
Cool. For clarity, we're using Travis (paid plan) on this repo, so it's likely as fast as a CI is typically going to be.

**Comment by greysteil** [comment]
I've just added an additional safeguard here - Dependabot will now check whether the last PR that was created over an hour ago also has no CI on it before deciding that the PR it is considering has no CI. That means if a provider is a little slow to update a PR it won't matter.

Thanks for flagging this one!

**Comment by danpalmer** [comment]
Amazing, thanks for such a quick response!

**Comment by jcjones1515** [comment]
FWIW, I saw this behavior tonight:

![image](https://user-images.githubusercontent.com/6596226/50127600-715eb600-0237-11e9-9344-95740969f027.png)

**Comment by jcjones1515** [comment]
@greysteil the PR description did not get changed, it is still "chore(deps): bump coverage from 4.5 to 4.5.2"

We are on the (paid version) of Travis CI using checks, not statuses

**Comment by greysteil** [comment]
Cool, I think I know what's happened here. Was this on an initial batch of Dependabot PRs?

**Comment by jcjones1515** [comment]
yes, it was on the initial batch

**Comment by greysteil** [comment]
@jcjones1515 - OK, here's what happened on that PR:
- Dependabot created the PR, along with a few others
- GitHub asked Travis to kick of a check suite run. This check suite was assigned the status "queued"
- A few minutes later, you asked Dependabot to merge the PR
- Dependabot checked whether it had any reason to believe CI was present on the PR, and decided it didn't
  - it disregarded the queued Travis check because the status was still queued (Travis hadn't responded with `in_progress` yet)
  - there were no old Dependabot PRs that had had CI run on them
  - Dependabot doesn't perform any checks on non-Dependabot commits
- Dependabot then assumed this was a repo without CI, and since you'd asked for a merge, performed it immediately

That's obviously no good - Dependabot should have realised that this repo *does* have CI. I've just fixed that:
- Dependabot now assumes repos have CI when they're initially created, and needs evidence that they don't to change that
- To get that evidence, Dependabot now checks whether any of the last 25 commits on your default branch had any kind of CI run on them

The above should make Dependabot a bunch more robust, and you shouldn't see any more cases like the above. Please do let me know if you do, though!

**Comment by jcjones1515** [comment]
@greysteil that totally makes sense, thanks for responding so fast.  I'll be adding other repos soon so I'll try this scenario again and see if it re-occurs.
