### ISSUE TITLE
Debugging Private Maven Repo Bumping

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#231]
Hi,

I have an issue with `pom.xml` bumping with a private maven repo.

* We use a hosted jFrog artifactory.
* I have configured what I believe to be the right credentials and URL in the config variables from the dashboard.
* I have one [successful example of a PR which bumped](https://github.com/marshmallow-insurance/uk-auto-policies/pull/260). 
* I have plenty of other repos that I expected to also be bumped, but nothing has happened. I've waited for one cycle of the normal scheduled bump time and also forced a bump via the UI.

In the case of the successful PR the dependency was:

```xml
<dependency>
                <groupId>com.marshmallow</groupId>
                <artifactId>uk-auto-proto-messaging-policies</artifactId>
                <version>0.0.4.RELEASE</version>
</dependency> 
```

and the PR has correctly raised:

```xml
<dependency>
                <groupId>com.marshmallow</groupId>
                <artifactId>uk-auto-proto-messaging-policies</artifactId>
                <version>1.0.1.RELEASE</version>
</dependency>
```

But, perhaps crucially, we **forgot** to specify in the `pom.xml`

```xml
  <repositories>
        <repository>
            <id>marshmallow</id>
            <name>uk-auto-releases-local</name>
            <url>https://our-org.jfrog.io/our-org/uk-auto-release-local</url>
        </repository>
    </repositories>
```

And _strangely_(?) dependabot has worked (perhaps because it just looks for anything it doesn't find in central in the configured variables from the dashboard. However, in other repos where we have the same dependency used:

```xml
<dependency>
                <groupId>com.marshmallow</groupId>
                <artifactId>uk-auto-proto-messaging-policies</artifactId>
                <version>0.0.4.RELEASE</version>
</dependency> 
```

and **did** specify 

```xml
  <repositories>
        <repository>
            <id>marshmallow</id>
            <name>uk-auto-releases-local</name>
            <url>https://our-org.jfrog.io/our-org/uk-auto-release-local</url>
        </repository>
    </repositories>
```

No bumping has happened. Is there something we should be aware of here, perhaps we have been doing this incorrectly or there is something else going on relating to maven. Any help appreciated. [Here](https://github.com/marshmallow-insurance/uk-auto-premfina-csv/blob/develop/pom.xml#L87) is an example of one which didn't 

---

Footnote: I am aware I link to private repos here that the general internet shouldn't have access to, these are provided as I presume the dependabot team can access these to help them debug.

**Comment by greysteil** [comment]
I'm slightly swamped today (still catching up from being at a conference last week) but will try to get to this today or tomorrow. Thanks for creating such a clear issue @davidgoate.

**Comment by davidgoate** [comment]
Thanks @greysteil hope the conference was good 🎉

**Comment by greysteil** [comment]
Finally got a chance to dig into this - turns out a bug in Dependabot was preventing it from using the config variable credentials if the repo was also specified in the `pom.xml` 🤦‍♂️ 
- That's fixed [here](https://github.com/dependabot/dependabot-core/commit/429e99206acc7ea3ba8e28299a2b9bc646d80c34)
- Separately, [this](https://github.com/dependabot/dependabot-core/commit/bf53acedabbbc0159fc021e4ad14f49e04514084) performance improvement also fixes it
- Finally, [this](https://github.com/dependabot/dependabot-core/commit/b28251be6007e22bcb05dcc19122eed220ade1b0) change means Dependabot will now raise a helpful error if authentication is stopping it from creating dependency updates, rather than silently ignoring the issue

Thanks for flagging this, and apologies for the bug!
