### ISSUE TITLE
Compatibility score is calculated only considering PR that are closed and not merged

### ISSUE THREAD

**Issue by AndreaGiardini** [dependabot/feedback#232]
In this case: https://dependabot.com/compatibility-score/?dependency-name=enzyme&package-manager=npm_and_yarn&previous-version=3.3.0&new-version=3.7.0

The compatibility score is lower than 100% because a pull request has been closed and not merged. On the other hand if we open the PR we can see that enzyme has actually been updated and dependabot closed the PR because it did not make sense anymore.

This is not a failed integration and should not be considered in the compatibility score

**Comment by greysteil** [comment]
Hmm, it sounds like we need to make the statuses for failing pull requests clearer on that page. The score is lower than 100% because the tests failed on that update, not because it was closed. In particular, it looks like `yarn test` failed in [this test run](https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/439874939).

@feelepxyz - worth taking another look at the design here, now that it's been out in the wild for a bit?

**Comment by greysteil** [comment]
(And thanks for the feedback @AndreaGiardini!)

**Comment by feelepxyz** [comment]
@AndreaGiardini @greysteil yes cheers! We can definitely make that more obvious! Will have a think 🤔
