### ISSUE TITLE
Maven multi module parent 

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#245]
Dependabot appears to have missed an update with a Maven multi-module project. 

Recently all of my non multi module projects got a PR for a Spring Boot update (such as [this one](https://github.com/marshmallow-insurance/uk-auto-legal-add-on/pull/52)) for `2.0.6.RELEASE` -> `2.1.0.RELEASE` of `spring-boot-starter-parent`.

[This particular repo](https://github.com/marshmallow-insurance/uk-auto-policies/blob/develop/pom.xml#L28) didn't and I'm not quite sure why.

---
Footnote, I am aware the links are private repos. They are intended to help the dependabot team diagnose if necessary.

**Comment by greysteil** [comment]
Just checked, and in this case it's because at some point (our DB says on the 16th of May) someone asked Dependabot to ignore v2.x.x of `spring-boot-starter-parent` on that repo.

Do you want me to remove that ignore condition for you? (We're planning a new version of the Dependabot dashboard that will make it *much* easier to see what dependencies you're ignoring.)

**Comment by davidgoate** [comment]
@greysteil wow, thanks for the update. Yes please that'd be amazing if you could. Is there any self service way to do this? I fear there might be other repos that could have a similar issue for me.

**Comment by greysteil** [comment]
Done, and I've removed the ignores on other repos, too.

At the moment there's no view to see what you're ignoring in Dependabot - it's something @feelepxyz is planning to work on soon, though.
