### ISSUE TITLE
Make requirement update style configurable

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#25]
This is a question mostly. 

For some reason in my `js` packages dependabot does not update `package.json`.
Link: https://github.com/wemake-services/eslint-config-flowtype-essential/pulls?q=is%3Apr+is%3Aclosed

This has actually resolved in this bug: https://travis-ci.org/wemake-services/wemake-vue-template/builds/382561571 

Dependency tree:
- wemake-vue-template (@dependabot is active)
- - eslint-config-flowtype-essential (@dependabot is active)
- - - eslint-plugin-flowtype (external dependency)

When `eslint-plugin-flowtype` was update to the new version I have merged [this PR](https://github.com/wemake-services/eslint-config-flowtype-essential/pull/6) to `eslint-config-flowtype-essential`. And released a [new version](https://github.com/wemake-services/eslint-config-flowtype-essential/releases/tag/0.2.0) of `eslint-config-flowtype-essential` with some changes.

Then I have received a PR for `wemake-vue-template`. That's when I have found a bug with `package.json`: https://github.com/wemake-services/eslint-config-flowtype-essential/commit/41a66576c2bd39f1eb38c1491bba72f25833bffa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R30

Why did it happen? That's how my `eslint-config-flowtype-essential` looks like:
<img width="520" alt="2018-05-23 13 37 48" src="https://user-images.githubusercontent.com/4660275/40419602-8247bf18-5e8e-11e8-9617-fa61b731696e.png">

Exactly the same happens for other libraries I maintain:
- https://github.com/wemake-services/stylelint-config-strict-scss/pull/7/files
- https://github.com/wemake-services/nuxt-imagemin/pull/7/files

But that does not happen to the `js` projects (which are not libraries!):
- https://github.com/wemake-services/wemake-vue-template/pull/519/files

Could you please explain what causes this inconsistency?

**Comment by greysteil** [comment]
This is by design, but it causes a bit of confusion - I should probably make it configurable.

For libraries, Dependabot tries to keep the version range in the `package.json` as wide as possible. If a new version is already covered, that means leaving the `package.json` alone and just updating the lockfile. The thinking here is that some people might be doing a flat install, so the library should specify wide version ranges for its sub-dependencies wherever possible.

For applications, the above logic isn't true - there's no reason for Dependabot to try to keep the version ranges wide, so it instead updates the `package.json` to make it as human-readable as possible. That means updating a `^6.9.1` requirement to `^6.9.2` for readability, even though it's not necessary for resolution.

Does the above make sense to you? I think it's the right logic but correct me if you'd prefer different behaviour for your libraries!

**Comment by sobolevn** [comment]
Yeap, that's confusing. 

I would prefer to have a setting for this. Personally, I would switch it to `update both`.

**Comment by greysteil** [comment]
This is configurable now! 🎉
