### ISSUE TITLE
Missing security PRs?

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#258]
I added a comment after #240 was closed, but I think it might've been missed. (In any event, I have more info on the issue now.) Basically what I'm seeing is that the Dependabot security PRs that have been opened in [this repo](https://github.com/panorama-ed/rainbow-backend) do not fully match GitHub's listed [security alerts](https://github.com/panorama-ed/rainbow-backend/network/alerts) for that repo.

I've reached out to GitHub support about the two Dependabot PRs that appear to be legitimate vulnerability fixes but are not in the security alerts list. I assume that's a GitHub bug and not a problem on Dependabot's end.

But there are also two security alerts in the GitHub UI that do not have Dependabot PRs, and I don't know if that's a problem on Dependabot's side. Does that make sense?

**Comment by greysteil** [comment]
Hey, sorry, I still have that comment in my emails to deal with!

Let me try to take a look into this now. Quite a busy period here, and I (tried to) take a day's holiday on Monday!

**Comment by greysteil** [comment]
No worries!

OK, so digging into this, it looks like you have quite a few out-of-date Dependencies on that repo, and have quite a few Dependabot PRs open. As a result, when Dependabot is cycling through your repo to create PRs it's timing out before checking all of the dependencies.

When a new security vulnerability is announced Dependabot kicks off a custom update run for just that vulnerability, so will always open a PR for it straight away. However, fo old security vulnerabilities it checks for updates in the course of its normal update cycle. Because that cycle isn't always finishing it isn't always finding the insecure dependencies and updating them.

One solution on the Dependabot side would be for me to make it always check insecure dependencies first, but that could cause Dependabot to *never* check other dependencies (for a pathologically slow to resolve dependency file), so I'm not keen on that. Another would be for me to boost Dependabot's infrastructure a little, which might be a good idea.

On your side, the thing that would help most would be to merge the dependency updates that Dependabot has already created. When a dependency is up-to-date Dependabot can short-circuit its resolution logic and skip over it (no need to do resolution if you're already on the latest version). That will allow it to cycle through all your dependencies each run, and you'll always get PRs for any out-of-date (or insecure) dependency then.

Apologies for the imperfect answer! Dependabot *does* have knowledge of all of the security vulnerabilities in the GitHub database, and has knowledge of lots of other ones too (from the Rubysec Advisory Database and from Sonatype's OSS Index).

Hope that helps clarify!

**Comment by JacobEvelyn** [comment]
Thanks for all the information, @greysteil! That's super helpful.

We adopted Dependabot to try to get our dependencies under control, and we've been hoping that a "slow and steady" approach would let us slowly dig our way out of the dependency hole we're in. It seems like we might not be digging fast enough though, so I'll see if on our end we can at least prioritize this repo's Dependabot PRs a bit more so it'll stop timing out.

To your thoughts on solutions:

> One solution on the Dependabot side would be for me to make it always check insecure dependencies first, but that could cause Dependabot to never check other dependencies (for a pathologically slow to resolve dependency file), so I'm not keen on that.

I actually think this is a great idea. If Dependabot's going to time out either way, I'd much rather it time out after making PRs for security fixes than just a few other dependencies. This seems in line with the fact that Dependabot makes immediate PRs for new security vulnerabilities—basically treating security PRs as the top priority.

> Another would be for me to boost Dependabot's infrastructure a little, which might be a good idea.

Of course I'm not opposed to this either. :)

One other thing—when Dependabot times out it would be great if we could be notified somehow. That way we'd more easily be able to prioritize merging PRs in the future for a repo that's timing out instead of being unaware that anything's not working correctly.
