### ISSUE TITLE
Dependabot should close GitHub gem bumps when superseded by RubyGems version

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#275]
Dependabot recently created [a PR to bump a gem dependency that was pinned to a GitHub commit](https://github.com/panorama-ed/rainbow-backend/pull/133). We no longer needed to pin it to a commit so we changed the dependency to [pull from RubyGems](https://github.com/panorama-ed/rainbow-backend/pull/448). I expected Dependabot to close its PR (and maybe it would have if I'd waited a bit longer?) but didn't see it do so.

**Comment by greysteil** [comment]
Thanks for the heads up! Looking through the transition history for that PR it looks like Dependabot was in the process of checking whether it still needed updating. It started checking that at 18:44:46 UTC, and the PR was closed at 18:46:11 UTC. My hunch is that means that you were just a bit too quick for Dependabot.

We're planning to do some work to speed up updates like the above - the lag is mainly due to Dependabot using big containers (that can run all of the languages Dependabot supports) that take a while to boot up. Hopefully we can get the delay down to ~30 seconds.

Thanks again for the feedback!
