### ISSUE TITLE
Dependabot force-pushing unnecessarily?

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#276]
This might be related to #152 and #153, but I noticed that Dependabot created [this PR](https://github.com/panorama-ed/rainbow-backend/pull/136), and if I'm reading GitHub's new UI correctly Dependabot has rebased the commit several times to remain current (see [0e7dacb](https://github.com/panorama-ed/rainbow-backend/commit/0e7dacb0e3ee04161b3357dfc1dea9d680ef854c), [ca5bab9](
https://github.com/panorama-ed/rainbow-backend/commit/ca5bab9db9e5a5467bbf28c13d243548abcfc003), [b5afab6](
https://github.com/panorama-ed/rainbow-backend/commit/b5afab6d378b9b8d5584cb065faf5cec53455932), [2fa002f](
https://github.com/panorama-ed/rainbow-backend/commit/2fa002ff9ffc0ab492bfdd3c9c15d5e24864e530), and [bedf46d](
https://github.com/panorama-ed/rainbow-backend/commit/bedf46d06f76ee43ed98c674e3fa065eec90cd26)).

This is great, as it means that if one Dependabot gem bump causes another Dependabot branch to fail, the latter will rebase, fail tests, and not be merged. But as mentioned in #152 this can result in a *_ton_* of CI runs.

I'm wondering if there could be an option to have Dependabot only auto-rebase when there are merge conflicts rather than every time. But I'm open to creative solutions here as well!

**Comment by greysteil** [comment]
Thanks for the feedback @JacobEvelyn.

This one's a little tricky, but I don't think we can easily reduce the number of rebases Dependabot does much, if at all here. The current setup is:
- Dependabot will always rebase if there's a merge conflict
- If you have a branch protection that requires PRs are always up-to-date before being merged, Dependabot will always rebase (you might want to switch automatic rebasing off entirely if that's the case and you want to leave Dependabot PRs open for a while for any reason)
- Otherwise, if a dependency file has changed, and the dependency being updated in the PR in question changed within it, then Dependabot will trigger a rebase. It needs to do this so that it knows to close Dependabot PRs if the dependency is updated elsewhere

My hunch here is that we want a `@dependabot rebase and merge` command, that makes it more convenient for folks who turn off automatic rebasing entirely. That way you can have the most efficient CI usage but still conveniently merge Dependabot PRs. What do you reckon?

**Comment by JacobEvelyn** [comment]
Sorry for the radio silence on this one. I'm not really sure what the best solution is here; we'll keep our eye on it and let you know if we get any ideas. `@dependabot rebase and merge` here might be a nice stopgap but I don't know how often we'd use it with a big green Merge button that we're used to clicking. :)

**Comment by jglick** [comment]
> a `@dependabot rebase and merge` command

This sounds a lot like the [Tide feature](https://github.com/kubernetes/test-infra/tree/master/prow/tide#features), FWIW.
