### ISSUE TITLE
What is the requirement before an update pr will be launched.

### ISSUE THREAD

**Issue by gerrywastaken** [dependabot/feedback#29]
I've noticed that many of our dependencies are not showing up with a PR when there is an update for the gem available. I can see new versions of rpsec-rails for instance: https://rubygems.org/gems/rspec-rails/versions/3.4.2

However there is no associated PR, while there are PRs for other gems.

**Comment by greysteil** [comment]
Hi @gerrywastaken,

This is almost certainly related to https://github.com/dependabot/feedback/issues/5. In a nutshell, the problem here is that you Gemfile (probably) has both `rspec` and `rspec-rails` in it, both of which are tightly linked to `rspec-core`. Since Dependabot only ever updates one top-level dependency at a time, updating either of the above is blocked by the other, and no update results.

I'm really keen to fix the above in Dependabot, but it's going to require quite a lot of work (we have the assumption that it's a single top-level dependency being bumped throughout our codebase). In the meantime, if you've got `rspec-rails` in your `Gemfile` you probably don't need `rspec` there, too.

**Comment by gerrywastaken** [comment]
We don't have `rspec` or anything else which depends on `rspec-core`, it could be one of the other dependencies though. Any way to figure this out?

**Comment by gerrywastaken** [comment]
Oh, this might be promising: https://github.com/dependabot/feedback/issues/32

**Comment by greysteil** [comment]
Hmmm, just tailed our logs whilst doing an update run for your repo (which I assume is the one we have for https://github.com/marketplacer). Turns out the bug is an infrastructure problem on our side: our boxes are running out of memory during the update, swapping, and then taking too long to finish.

Two solutions:
1) I'm going to jump on https://github.com/bundler/bundler/issues/6114, which I think is the route of the problem
2) It looks like there are lots of un-merged PRs on your repo, which Dependabot is recalculating during each update run. If you were to merge some of the open PRs (which I appreciate are probably for major version bumps) it would allow Dependabot to skip over them much more quickly, and prevent it from timing out before it gets to `rspec-rails` etc.

(I appreciate 2. is a shitty suggestion, and that this is a problem with our infrastructure! I'll fix it, but if you want to get things working in the shorter term, that's the way to do it.)

**Comment by greysteil** [comment]
FYI, https://github.com/CocoaPods/Molinillo/pull/90 will go some way towards fixing this. I'll pull it in as soon as it's merged.

**Comment by gerrywastaken** [comment]
@greysteil Wow, thanks for looking into this in great detail, I really appreciate that. I'll run it by the team and see what they think.

**Comment by greysteil** [comment]
OK, I've pulled in that update, and also randomised the order that Dependabot processes dependencies, so even if our update runs are timing out it won't preclude you from ever getting an update. I'd like to do more on this, but the optimisations required are non-trivial (and ultimately need us to switch hosting provider).

**Comment by gerrywastaken** [comment]
@greysteil That's a great idea, thanks for adding it and yet again improving Molinillo. I haven't seen any new different PRs come though yet, but I'll update here as soon as I do.

> I'd like to do more on this, but the optimisations required are non-trivial (and ultimately need us to switch hosting provider).

No worries, this solution sounds good. As for the server, I hear you are not yet charging for the Dependabot. Maybe that should change so that you can possibly hire others as it seems like you are currently flooded with some big tickets. 👍

**Comment by greysteil** [comment]
Thanks @gerrywastaken. We've just got into the GitHub marketplace and started charging for the service, but early adopters like yourselves still get it for free. If you'd like to pay, you can set your organisation's plan [here](https://github.com/marketplace/dependabot).

Psyched to be powering through those tickets and have more and more people using Dependabot!

**Comment by gerrywastaken** [comment]
Plan changed now apparently. :) Thanks again Grey.
