### ISSUE TITLE
Closing issue without command

### ISSUE THREAD

**Issue by pascalberger** [dependabot/feedback#300]
Dependabot just closed a PR without that the corresponding command was given. Instead I updated the branch manually and by mistake pushed a version where no changes were included.

PR is https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/pull/109

**Comment by greysteil** [comment]
Thanks for the heads up. From looking at the events in the stream on that PR it looks like GitHub thinks you closed that PR, rather than Dependabot:

![image](https://user-images.githubusercontent.com/1144873/50058113-d64cda00-016b-11e9-8fe0-1d64d3c93666.png)

Is that possible? I can't see anything in the logic on Dependabot's side that would cause this.

**Comment by pascalberger** [comment]
You're right. Seems like GitHub closes PRs without commits and depandabot reacted to this. Sorry, I missed the info that GitHub closed it (in my name).

Btw. underlying issue why I needed to modify the PR in the first place was this: https://github.com/dependabot/feedback/issues/259. Depandabot only updated packages.config file, but not csproj.

**Comment by greysteil** [comment]
👍 and thanks for the push on that issue.

In the meantime, I've updated Dependabot's logic so it *won't* comment about re-opening the PR if the close occurred because you pushed over Dependabot's commit (as it was a little unclear).
