### ISSUE TITLE
Renamed repo, no longer in the list

### ISSUE THREAD

**Issue by Stanzilla** [dependabot/feedback#308]
I renamed a repo and it now no longer shows up in the dependabot list, also would be nice if you had an option to trigger a resync with the GitHub account.

**Comment by greysteil** [comment]
Hmmm, that's odd. Did you already have your Dependabot dashboard open when you renamed the repo? I can see how that would cause issues, but otherwise this should already be handled.

If you point me to your account and give me details of the repo name before and after then I can dig into it.

**Comment by Stanzilla** [comment]
I could have had it open already, don't really remember, sorry.

The repo I renamed is https://github.com/Stanzilla/WeakAuras-Companion and it was called https://github.com/Stanzilla/wa-update before.

**Comment by greysteil** [comment]
Just dug into this and it's a little tricky. Dependabot uses the GitHub GraphQL API to check which repos a user has access to, and unfortunately the only way to specify repos in this request is using organization and name, rather than GitHub ID. That's causing problems when a repo is renamed, particularly when combined with GitHub not sending webhooks for renamings.

Dependabot *does* automatically resync repo details each time it does an update run for a repo - I've just triggered an update run for the repo (which had the old name in our DB) on your account and it's fixed things up.

I think there might be a solution to the above if Dependabot persists the `node_id` that GitHub uses in the GraphQL API. I need to look into the details, but I'll try to get that done today.

**Comment by Stanzilla** [comment]
Thanks for the help, do we want to keep the ticket open as long as you investigate?

**Comment by greysteil** [comment]
Let’s keep it open - I should have this fixed tonight

**Comment by greysteil** [comment]
OK, this should be fixed properly now - we now store the GitHub `node_id` as well as the normal ID, which means we can use that to fetch repos that are accessible to a user, rather than relying on the repo name.

Thanks for the feedback on this one!
