### ISSUE TITLE
Missing security PRs?

### ISSUE THREAD

**Issue by beaugunderson** [dependabot/feedback#320]
These two, for example show up in GitHub but had no Dependabot PR created:

![screenshot](https://i.imgur.com/i4zjSyp.png)

This is on `canvas-medical/canvas`.

**Comment by RohanNagar** [comment]
I have the same security alert for `pyyaml`, but no Dependabot PR (I'm using Pipenv)

**Comment by greysteil** [comment]
I'm guessing this is because `pyyaml` is an indirect dependency in `canvas-medical/canvas`, and is currently at v3.13. Bumping it to v4.1.0 would probably require a non-security update to a top-level dependency, and Dependabot doesn't realise that it should make that update to enable this one (since you've got Dependabot in security-only mode.

We could do better here, but it's hard! For Python we don't yet support creating PRs that update multiple dependencies, so getting Dependabot to a point where it can figure out what it needs to update here isn't an easy fix.

The same is almost certainly true of the `webpack-dev-server` update, too - it's has a peer dependency (`webpack`), and updating it would require updating that peer dependency too.

Again, we could do better here, and the prognosis is a little better - Dependabot already knows how to create multi-dependency PRs for JS, so it might not be too tricky for me to tweak things so that it creates a PR here. I'll take a look tomorrow, but in the meantime I'd recommend updating those dependencies manually.

**Comment by beaugunderson** [comment]
Thanks @greysteil, appreciate the thorough explanation!

Since starting to use Dependabot I've begun to pay less attention to the GitHub emails/alerts, but given the limitations you mentioned it makes sense to continue to be diligent about them.

**Comment by greysteil** [comment]
Yes! I’d also like to have Dependabot create issues for vulnerabilities it can’t resolve - we have a separate issue for that I believe.
