### ISSUE TITLE
React-Redux 6.0.0 not suggested as an update

### ISSUE THREAD

**Issue by shepmaster** [dependabot/feedback#339]
The [React Redux package](https://www.npmjs.com/package/react-redux) version [6.0.0](https://www.npmjs.com/package/react-redux/v/6.0.0) was released "two months ago", but the repo at https://github.com/jetpackworkflow/checklistpro has not received a notification for that package since 5.1.1.

See also a previous interaction in #294; perhaps something similar is at play?

It would be nice to have the web UI show versions that we have requested to be ignored, in order to rule out user mistakes on our side before asking for help! ❤️

**Comment by feelepxyz** [comment]
@shepmaster hey this is due to `redux-little-router` having a peer dependency requirement on react-redux which only allows versions: `^4.0.0 || ^5.0.0"`

Seems like this router is deprecated and probably wont get any updates to fix this: https://github.com/FormidableLabs/redux-little-router

We're planning on building a page in the dashboard that will give you visibility on installed versions and which ones have been ignored/not possible to install.

https://github.com/dependabot/feedback/issues/72

**Comment by feelepxyz** [comment]
@shepmaster thanks for getting in touch!

**Comment by shepmaster** [comment]
>  this router is deprecated

Yeah, we have an item in our tech debt backlog to replace it. Didn’t realize it was blocking anything else!

> visibility on installed versions and which ones have been ignored/not possible to install

Sounds wonderful; thanks so much!
