### ISSUE TITLE
PR title, release notes for github URLs with semver tags

### ISSUE THREAD

**Issue by SethDavenport** [dependabot/feedback#344]
Hi there,

I'm trying to understand a difference in the way dependabot creates PRs for our internal, github-tag based packages, and external npm packages.

Specifically, when we get a 3rd party update, the PR looks like this (which is great):

![image](https://user-images.githubusercontent.com/4614141/51862129-eb408f80-230b-11e9-9a41-742ee95237a9.png)

- the title contains the old and new versions
- the PR description includes a snippet from the dependencies 'releases' page on Github.

For our internal packages, we "release" by creating a new github release in the private repository. This creates a tag and lets us enter release notes the same way prettier does it. However instead of pulling from npm, we use a github URL in our package.json:

`"@mycompany/mylib": "git+ssh://git@github.com/mycompany/mylib.git#^13.5.0",`

In this case, the PR ends up looking like this:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/4614141/51862423-99e4d000-230c-11e9-8a40-f964023256b0.png">

By comparison:
* the title just contains commit hashes 
* the description seems to be unable to locate our repo's release notes on github.

This is making it tricky for us to flag major versions/breaking changes internally.

Dependabot seems to be aware of our release tags at some level because it's updating the package.json correctly. I'm assuming I just have something configured wrong.

FWIW here's our config.yml:

```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
version_requirement_updates: "widen_ranges"
```

We are using `yarn`.

**Comment by greysteil** [comment]
Hey Seth,

It's slightly tricky to debug this one without details of the PR - if you ping a link to it to support@dependabot.com that will be enough for me to find it in our backend.

More generally, Dependabot's metadata lookup logic for JS is [here](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/metadata_finder.rb#L37-L47) - in this case it looks like it's finding the source but not looking for a changelog or release notes because the change is to a git commit, rather than between defined versions (it would do the later if you were using tags, for example).

**Comment by SethDavenport** [comment]
Link sent to support@dependabot.com as requested. The weird thing is that we are using tags. The commit hashes correspond to the two tagged releases that match the package.json diff generated by dependabot.
