### ISSUE TITLE
Ability to manually replace a version org wide

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#355]
# Issue Encountered 
We've recently come up against an issue with a dependency that doesn't get suggested to be bumped in a Dockerfile (`adoptopenjdk/openjdk11:jdk-11.28-alpine-slim` -nov 9th 2018)

There is a seemingly newer version `adoptopenjdk/openjdk11:jdk-11.0.2.9-alpine-slim` (published feb 4th 2019). I appreciate that this appears to be poorly versioned on their side (`11.0.2.9` apparently newer than `11.28`), which I presume is why dependabot doesn't try to bump this.

# Feature Request
However, this leads me to a potential feature request. To remedy this situation, my current thinking is that I'd need to go through each repo in our org (18 repos impacted) and manually bump this. On the other hand, dependabot already has access to all of these and understands how to create PR's etc. If I could somehow say to dependabot please scan all repos to replace dependency `x` with `y` then in theory it could handle this for me... 

The one things I'd then be unsure about is whether it'd then immediately suggest on the next scan that  `11.0.2.9` gets "updated" to `11.28`. 

I'd be interested to hear whether this is against the fundamental ethos of what you intend dependabot to be about, but I do see it as a potentially useful feature for org wide dependency changes for cases that are outside of our control (where authors have poorly versioned their artifacts).

**Comment by feelepxyz** [comment]
@davidgoate thanks for getting in touch! Where are you seeing this version published? Having some issues googling for this so might be looking in the wrong places.

**Comment by greysteil** [comment]
@feelepxyz - it's https://hub.docker.com/r/adoptopenjdk/openjdk11

**Comment by feelepxyz** [comment]
Oh yeah annoying! Looks like they've changed the versioning scheme from that first release.

@davidgoate could you email support@dependabot.com with an example repo I could test this against? Just want to make sure we're not doing the wrong thing here.

**Comment by greysteil** [comment]
Just took a dig into this. On the way Dependabot should be handling this as part of its normal business:
1) Previously, Dependabot wouldn't have been able to update this dependency, because its versions include both a prefix and suffix around the version number. I've just fixed that in [this commit](https://github.com/dependabot/dependabot-core/commit/1271efcfd4c43ff27e8b72a5ed340a687d56c9b3). I'm pretty sure it won't break anything else, but if it does I'll look into that.
2) Additionally, because of the funny version scheme change, there's no way that Dependabot could know to update from `11.28` to `11.0.2.9`. Despite `11.0.2.9` matching the `latest` tag, if you're already using `11.28` Dependabot will assume that you're on a pre-release. That's correct behaviour, except in this weird case, so I can't work around it. If you were on `11.0.2.7`, however, it would correctly update you to `11.0.2.9`.

On the content of this issue (requesting an update across projects):
- We can't support this in Dependabot as it currently stands, so I'm going to close this issue. Supporting it would require a bunch of work to make Dependabot kick off tasks that create updates to a specific version, which isn't how it currently works, and the benefit isn't big enough
- That said, I think this is a good idea. I've been musing on more general ways Dependabot could be helpful, and one is by building it out as a bot interface for CI commands in general (`@dependabot fix rubocops`, `@dependabot bisect commits to find breaking change`, etc.). We're not in a position to implement these right now, but in partnership with a CI provider I can see how we could do some really cool stuff. I'll keep you posted on this one. 🙂
