### ISSUE TITLE
Show config file errors in dashboard if issues are disabled on a repo

### ISSUE THREAD

**Issue by cabello** [dependabot/feedback#357]
Hi 👋 

Hope you are doing great!

I just noticed that a project we set up for weekly updates is doing daily updates, here's what I find:

While visiting dependabot website:

![screen shot 2019-02-06 at 8 22 01 am](https://user-images.githubusercontent.com/60936/52344266-4ea37f00-29e8-11e9-9d5e-4a04b2506b11.png)

While visiting github latest master:

![screen shot 2019-02-06 at 8 22 41 am](https://user-images.githubusercontent.com/60936/52344304-64b13f80-29e8-11e9-9eef-d153933e9d5e.png)

Maybe there is a typo or a missing configuration? You can check our account, the project id is 24541.

Thanks,
Danilo

**Comment by greysteil** [comment]
Just took a look at this. It looks like you have issues disabled on that repo, so Dependabot has been unable to tell you that the above config file isn't valid (because of the indentation on line 7). As a result, Dependabot is still using the original setup for that repo.

There's definitely an improvement we can make on our side for cases like this: we should be showing you details of the problem in your dashboard if you don't have issues enabled. I'll look into adding support for that today, but in the meantime, if you indent line 7 so that it aligns with line 6 your config file will be valid, and Dependabot will update.

**Comment by cabello** [comment]
Thank you, that fixed it! 🙏

**Comment by cabello** [comment]
Sorry, did not mean to close it given the new title.

**Comment by greysteil** [comment]
No worries - working on the fix now 🙂

**Comment by greysteil** [comment]
Fix deploying now. Thanks again!
