### ISSUE TITLE
Recent released versions of gems did not trigger new PR when using "Live Updates"

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#361]
For some reason, when rubocop 0.64.0 was released yesterday, it did not trigger a new PR on my project.

https://app.dependabot.com/accounts/tablexi/projects/562

I have my project set for "Live Updates".

It looks like this may have been happening for some time..as my project only has `autoprefixer-rails 9.4.5`, though `9.4.6` (Jan 21) and `9.4.7` (jan 28) have been released., and `bundler-audit 0.6.1` was released Jan 18th.

It appears likely that something happened early january.

**Comment by greysteil** [comment]
Just dug into this. It looks like you have three open PRs on that repo, and have the maximum number of open PRs per language/repo combination configured to three in your account settings. As a result, Dependabot is only creating new PRs when you merge an old one. You can update that limit [here](https://app.dependabot.com/accounts/tablexi/settings).

In this case, however, I think Dependabot could also be doing better. The PR it should be opening would supersede an existing one, and I think it should be able to break its maximum PRs limit temporarily in order to do that. I'll make that change on our side.

**Comment by greysteil** [comment]
(Code updated and you should have a PR for the latest version of Rubocop now. Thanks for the feedback!)

**Comment by rdunlop** [comment]
@greysteil thank you very much for the detailed explanation. I guess someone else at the company applied that limit. This repo used to be unlimited PRs. Is there any way to configure the number of open dependabot PRs on a per-repo basis?

**Comment by greysteil** [comment]
Not yet, but it's something we'd like to move to be configurable at the repo level now we've got config files. Give us a couple of weeks on it.
