### ISSUE TITLE
Add setting to define custom command to use for generating the requirements file

### ISSUE THREAD

**Issue by arthurio** [dependabot/feedback#366]
Here I'm going to give a python usage example but I think it could be a generic feature for other languages as well. We use `pip-tools` to generate our requirements. However, we split our dependencies in `dev-requirements.in` + `requirements.in` and we use a handmade script to generate both `dev-requirements.txt` (from `dev-requirements.in` + `requirements.in`) and `requirements.txt` (only from `requirements.in`). Instead of dependabot running `pip-compile`, we'd want it to run our custom script `./pip-compile.sh`.
Is it already possible but I missed the setting?
Or would you consider adding a setting via the config file?

**Comment by greysteil** [comment]
Thanks for the feedback.

Dependabot has some logic to try to figure out the order of compilation automatically ([here](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L334-L368)). Have you already tried it and found that's not working?

My general principle with Dependabot has been to have it try to work out the right thing to do automatically, rather than lean on settings, and we've got surprisingly far with that.

**Comment by arthurio** [comment]
The default behavior didn't work, but looks like using `-r requirements.in` in `dev-requirements.in` will work for us since we pin exact versions (see also: https://github.com/jazzband/pip-tools/issues/398#issuecomment-261252209). I'll give that a spin, thanks for the follow up!
