### ISSUE TITLE
Dependabot vs Greenkeeper

### ISSUE THREAD

**Issue by styfle** [dependabot/feedback#38]
How does [Dependabot](https://dependabot.com/) compare with [Greenkeeper](https://greenkeeper.io/)?

They both require *"Write access to code"* which seems unnecessary to open a pull request.

Are there any differing features?

**Comment by greysteil** [comment]
We're obviously biased, which is why we haven't published a comparison, but here are some things I know we're different on:
- Dependabot brings you up-to-date one dependency at a time, as opposed to Greenkeeper's initial bump-all-the-packages pull request
- Dependabot updates your lockfile (yarn on npm5) as part of the normal update process. Greenkeeper requires that you add a script to your CI service to do this, which then commits back to  your repo, causing your tests to be run twice on each Greenkeeper PR
- Greenkeeper gives you updates "in real time", whereas Dependabot gives you them each morning (/week / month)
- Greenkeeper can bump your node version for you. Dependabot can't
- Dependabot is multi-language (obviously)
- Dependabot automatically rebases its PRs if/when there are merge conflicts. I don't know if Greenkeeper does this or not (and it's important, because you'll often get merge conflicts in your lockfiles)

On the _"Write access to code"_ requirement, we don't ask for that for fun! We need it to be able to create a branch and push to it on your repo (which means that your test setup gets run). Particularly for private repos, that's the flow you'd expect. Admittedly for public ones you might expect us (or greenkeeper) to clone your repo, push to our own fork, and then open a PR, but we prefer the simplicity of it working the same way for both public and private repos, and the certainty that it's your test setup running (with all relevant environment variables, etc.).

Hope that helps a little. The guys at Greenkeeper are great, so if you plump for them we really have no hard feelings!

**Comment by styfle** [comment]
Thanks for the detailed response!
I'll give dependabot a go and see how I like it 👍

**Comment by StephanBijzitter** [comment]
@greysteil 
>Dependabot automatically rebases its PRs if/when there are merge conflicts.
Our repository (can't name it here, don't want it on Google's index) does not actually rebase automatically.

If there is no conflict, asking Dependabot to rebase does work correctly.
If there is a conflict, we have to manually rebase.

I first thought it was a bit of a timing issue (maybe it checks every hour?), but at the end of the work day (like 7 hours later), it still didn't automatically rebase. So there's some problems there.

**Comment by greysteil** [comment]
Hmmm, you shouldn't have to do that - ping me an email on support@dependabot.com and I'll look into what's going on with your repo.
