### ISSUE TITLE
How live updates are done ?

### ISSUE THREAD

**Issue by waghanza** [dependabot/feedback#382]
Hi,

I have configured `live` updates for **php:composer** in https://github.com/the-benchmarker/web-frameworks/blob/master/.dependabot/config.yml#L153

As the doc says this will create a `PR` inside the repository on https://packagist.org upload

However, I can see that https://packagist.org/packages/laravel/framework has been updated ~16 hours ago. 

When updates are made on @dependabot-bot side ?

Regards,

**Comment by waghanza** [comment]
@greysteil Maybe related to https://github.com/dependabot/feedback/issues/379

**Comment by greysteil** [comment]
Huh, I'm not sure how we can have missed that, unless there was a mass of other dependency releases that happened at the same time.

Dependabot uses [this endpoint](https://packagist.org/feeds/releases.rss) to poll for recent PHP releases. It hits it once a minute, and triggers updates for all users who have `live` updating enabled immediately.

I've looked in our DB, and we didn't trigger any updates for `laravel/framework` in response to yesterday's release. We *are* picking up updates from that endpoint, though - today's `laravel/dusk` update was picked up just fine.

In addition to live updates, Dependabot run a daily catchup job, to ensure that anything it has missed still gets processed. That's why you got a PR for `laravel/framework` this morning.

My hunch is that a large bunch of dependencies were released at once about the time that `laravel/framework` was, meaning the releases feed didn't include the Laravel update when Dependabot checked it, but I'll keep an eye out for this happening again. The changes in #379 should make this much less likely, but they were already deployed when this happened. 😕
