### ISSUE TITLE
Dependabot may be excluding files in checkout

### ISSUE THREAD

**Issue by hlascelles** [dependabot/feedback#393]
We have some external code that configures our Gemfile, and one is a dotfile. eg (simplified example):

Gemfile
```ruby
source 'https://rubygems.org'

require_relative 'helpers/gem_helper'

gem "awesome_print"
```

`helpers/gem_helper.rb`
```ruby
require_relative "other_file"
does_checks_on_bundler_version
```

`helpers/other_file.rb`
```
does_checks_on_ruby_version
```

Currently Dependabot fails, saying:
```
Bundler::Dsl::DSLError with message: 
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /home/dependabot/dependabot-updater/dependabot_tmp_dir/helpers/other_file. Bundler cannot continue.
```

It looks like Dependabot *is* correctly pulling in *some* external ruby files. In this case, it correctly pulls in the first external ruby file `helpers/gem_helper.rb`. But further requires do not succeed (eg `require_relative "other_file"`). Also, various other dot files are not further discoverable.

We've done a number of scenarios and checks but cannot determine which files are present easily. Is there a known rule we can follow?

**Comment by greysteil** [comment]
Thanks for the feedback @hlascelles.

The code for Dependabot's file fetching logic is [here](https://github.com/dependabot/dependabot-core/blob/master/bundler/lib/dependabot/bundler/file_fetcher.rb) and you're quite right - it fetches `require_relative` files, but only one level of them.

This is the first time I've seen a setup where you've got nested `require_relative` calls in a Gemfile. Would it be straightforward for you to refactor that setup, or is there a reason you're using it? Since Dependabot doesn't clone your repo it's tricky for us to support.

**Comment by hlascelles** [comment]
Thanks for the steer @greysteil. Yes, it would be a relatively easy change. Cheers!
