### ISSUE TITLE
Add support for symfony.lock (and potentially other dep manager plugins)

### ISSUE THREAD

**Issue by nesl247** [dependabot/feedback#398]
symfony/flex is a composer plugin that is used for the Symfony framework. It uses it's own `symfony.lock` file in order to determine if certain `recipes` need to be run. These create example configs and such for installing bundles (integrations) into the framework.

It would be great if Dependabot would either include that in it's commits, or have a configurable way for it to happen.

**Comment by greysteil** [comment]
Thanks for the feedback @nesl247.

This one has history! There's an issue [here](https://github.com/dependabot/dependabot-core/issues/625) which I think is still up-to-date. Since Dependabot doesn't clone your repo there's no way for it to install the bundles etc. for you.

Perhaps a good candidate for a GitHub Action? I'm going to close because it can't live within main Dependabot.

**Comment by nesl247** [comment]
Thanks for the info.
