### ISSUE TITLE
Issue with Python requirements update

### ISSUE THREAD

**Issue by merwok** [dependabot/feedback#411]
Hello!  A PR was opened on a private repo to `Bump flake8 from 3.6.0 to 3.7.7`.  The new version has some dependency changes (warning for huge diff page):
https://gitlab.com/pycqa/flake8/compare/3.6.0...3.7.7#02a4515ab9c2c9b0da68e82954a299af48837e35
https://gitlab.com/pycqa/flake8/compare/3.6.0...3.7.7#8e2edce0d507e1297474f25c00cae94258db38d8

PR diff only changed flake8 (in `deps/tests.txt`, created with pip-tools) so CI for the PR failed:
```
flake8 3.7.7 requires entrypoints<0.4.0,>=0.3.0, which is not installed.
flake8 3.7.7 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.4.0 which is incompatible.
flake8 3.7.7 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 2.0.0 which is incompatible.
```

**Comment by greysteil** [comment]
Hmmm, that's odd. We have [this logic](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/file_parser.rb#L130-L136) to determine whether a `.txt` file is a compiled file from pip-tools. Without looking at your full setup it's hard for me to know why that didn't pick things up here - can you give more detail?

**Comment by merwok** [comment]
dependabot is configured to update `runtime.txt`, `tests.txt`, `deploy.txt` and `ci.txt` in a sub-directory `deps`; they all have the matching `.in` file.

(BTW I was very pleasantly surprised on another project after I activated hashes for pip-compile and dependabot picked that up! :slightly_smiling_face:)

What kind of details do you need?
Should I try setting up a new, public project with `flake8 3.6.0` in the txt file and see if the same problem arises?

**Comment by greysteil** [comment]
If you're happy to put the requirements files from your setup in a public project then we can debug it together there. Otherwise, if you're happy for me to step through a Dependabot update run on your repo locally (Dependabot will pull down the dependency files onto my machine whilst I do so, but nothing else) and email me with the URL of the dodgy PR I should be able to figure out what's going on from there.

**Comment by merwok** [comment]
Not much time this week so sent you an email.

BTW I haven’t been to the dependabot dashboard in a while, a new thing is a warning about «expected to find one at the path: /deps/requirements.txt» but I don’t have one file with that name, and PRs are happily coming for other txt files in `deps`.  Is this a known issue?

**Comment by greysteil** [comment]
Ack, this one is embarrassing. Turns out, both issues (the dashboard error and the bad upgrade) are because Dependabot was being too picky about what txt files it thought were requirement files. I've fixed that in [this commit](https://github.com/dependabot/dependabot-core/commit/f92588191e9f5cb90b4b3d535c9a8e4bb0b8ca1b) and validating that it correctly updates your repo now. Sorry about that, and thanks for the feedback - it's the way Dependabot keeps improving. ❤️

**Comment by merwok** [comment]
OK I’m waiting for the rebase!

(Web UI still has the issue but I guess you haven’t deployed that yet)

**Comment by greysteil** [comment]
Indeed - deploy going out in the next 5 mins!

**Comment by merwok** [comment]
Fix confirmed!
