### ISSUE TITLE
Add an option to only do Cargo.toml updates

### ISSUE THREAD

**Issue by thomaseizinger** [dependabot/feedback#423]
Unfortunately, #417 is unlikely to be implemented soon.

Could we, in the meantime, have an option to have dependabot only do `Cargo.toml` updates and ignore updates that only touch the lockfile (since those are "easily" done in one go with a manual `cargo update`).

Put differently, it would be helpful to have an option here:

![image](https://user-images.githubusercontent.com/5486389/55441609-1ccd2400-55f7-11e9-9925-d203d8d8ca45.png)

that represents the inverse of the 2nd one.

**Comment by feelepxyz** [comment]
@thomaseizinger I'm not sure I follow exactly, would you like to only do updates that require both Cargo.toml and lockfile updates? If so, you should be able to do this with the option you have selected, "only top-level dependencies".

You could also disable security updates that only touch the lockfile if you use the config file and specify allowed updates that only match direct dependencies:

```
allowed_updates:
  - match:
      update_type: all
      dependency_type: direct
```

Is this what you are after?

**Comment by thomaseizinger** [comment]
> You could also disable security updates that only touch the lockfile if you use the config file and specify allowed updates that only match direct dependencies:

Yes that is what I was looking for, thank you :)

**Comment by D4nte** [comment]
@feelepxyz we added the following dependabot configuration: https://github.com/comit-network/comit-rs/pull/867

But yet, dependabot opened this PR that updates the Cargo.lock only: https://github.com/comit-network/comit-rs/pull/884

I thought that the `dependency_type: direct` would prevent that.

**Comment by feelepxyz** [comment]
@D4nte oh yeah looks like we might not be filtering out indirect dependencies for Rust. Will see if this is something we've missed.

**Comment by feelepxyz** [comment]
@D4nte hey sorry for the delay on this, the PR you linked to only updated the lockfile because the requirement in your manifest allows any  `0.9.x` version: https://github.com/comit-network/comit-rs/blob/master/application/comit_node/Cargo.toml#L31

You could fix this by specifying a full version for all your dependencies in your `Cargo.toml` so both files always have to be updated.

**Comment by D4nte** [comment]
@feelepxyz thanks for the prompt response.

I don't think your proposal matches our requirement.

1. We are keeping "0.9" (patch version not specified) in the manifest on purpose because as we are happy with getting the latest non-breaking change patch.
2. We want to handle cargo.lock only update ourselves so we can batch then with a local `cargo update`. Whether a cargo.lock only update is a due to a direct dependency (dependency specified without a patch version in cargo toml) or an indirect dependency.

Is that something possible with dependabot?

**Comment by feelepxyz** [comment]
@D4nte ah sorry yeah that combination won't work with Dependabot unfortunately! Is this mainly to reduce the number of builds you run on CI? We've got quite a lot of feedback on this and are planning on doing work to allow you to group PRs but will be a while until we get to it.

**Comment by D4nte** [comment]
Yes correct, reduce the numbers of builds on CI and number of PRs to review.
Thanks for the info.

**Comment by feelepxyz** [comment]
@D4nte cool, thanks for the feedback! And sorry that we don't have a better solution in the near term. Definitely keen to tackle this problem as it's cropping up quite a bit.
