### ISSUE TITLE
Support for Bitbucket Cloud

### ISSUE THREAD

**Issue by jdesulme** [dependabot/feedback#439]
I notice you have native support for Github and Gitlab. Is there anything for Bitbucket cloud (https://bitbucket.org) on the horizon?

**Comment by greysteil** [comment]
It's on our list, but not imminent - we won't have it before June (unless, of course, you want to put together a PR!)

**Comment by ozbillwang** [comment]
June now. Any updates?

**Comment by greysteil** [comment]
I couldn't write about this previously because we were in acquisition talks, but GitHub's acquisition of Dependabot changes things here.

We're now working on integrating Dependabot directly into GitHub, and won't be adding support for Bitbucket into dependabot.com. We will, however, continue to accept pull requests and maintain Dependabot Core to add Bitbucket support and extend its GitLab support. That means you'll continue to be able to use Dependabot Script with GitLab, and if/when Bitbucket support is added to Dependabot Core you'll be able to use that script with Bitbucket too.

Hopefully that helps clarify, and apologies if it doesn't provide exactly what you were looking for. I'm going to close this as answered, but feel free to ask anything else.

**Comment by ozbillwang** [comment]
Understood, thanks for updating

**Comment by VictorioBerra** [comment]
I would just like to throw my vote into the hat here for on-prem BitBucket support if/when anyone takes on that PR challenge. Maybe we could have some way to pay/sponsor the development?

**Comment by gruckion** [comment]
Can I work on this with some support from the key team? I am willing to pick this up as I need it. Is this an option?

**Comment by subpx** [comment]
@``
