### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by spmason** [dependabot/feedback#445]
It'd be awesome if, instead of just blindly bumping dependencies, dependabot could perform some analysis and try and find out whether a dependency is unused first - then raise a PR to remove that dependency instead!

We've got some older repos that dependabot is working through, and I've noticed on a few bumps that the dependency in question has been refactored out and the person doing this has forgotten to check whether it's still used.

It's super-easy to update the PR dependabot opened to manually remove the dependency, but dependabot would be an even bigger boon for repository hygiene if it did this automatically

Obviously this is probably a lot of work, and would need custom dependabot commands like "please don't try to remove this dependency", but it would make a great feature IMO

**Comment by simlu** [comment]
The problem is that dependabot would need to understand the code. This is not a trivial task. We are doing this as part of our generic test suite (using [js-gardener](https://github.com/blackflux/js-gardener/blob/master/src/subtasks/depused.js)) and I would recommend you go down a similar route. The underlying dependency powering this is [npm-check](https://www.npmjs.com/package/npm-check) (it's not perfect, but pretty good).

If you're using a different programming language that JS there might be other packages doing similar things. However, as I said, this is not a trivial task and should imo not be a responsibility of dependabot.

**Comment by greysteil** [comment]
Yeah, this would be really awesome, but Dependabot isn't positioned to do it yet.

Critically, Dependabot never clones your repo, so currently it can't know whether a dependency is used or not. We may change that at some point, but for now I think this would have to be a separate service.

Thanks for the feedback all the same (and thanks @simlu for the pointer to `npm-check`).

**Comment by spmason** [comment]
Like I said, I understand it’s a lot of work, but I think it’d be a great feature for dependabot to have that sets it apart from the competition.

I’m aware there are other packages out there to do it for me (the Maven dependency plugin has a similar feature), but they aren’t easily automated, at least to the extent that dependabot makes life easy for me. I’m not sure i’d pay for a separate service that *just* cleaned up old dependencies. It does seem like something that would closely fit with dependabot’s purpose

**Comment by greysteil** [comment]
Yeah, agree with the fit. The repo cloning is just such a pain - having your entire repo checked out when we're considering dependency updates would be a big security risk. We have some interesting stuff up our sleeve that could make this more straightforward in future, though 🙂

**Comment by spmason** [comment]
Thanks - it’s great that you don’t clone the entire repo, I can see how hard this feature might be without the code!
