### ISSUE TITLE
Vue update failed

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#45]
While updating `vue` to version `2.5.3` dependabot breaks the build, since it is required to have the same version of`vue-template-compiler`.

```
Vue packages version mismatch:
- vue@2.5.3
- vue-template-compiler@2.5.2
```

Here's a link to the build: https://travis-ci.org/wemake-services/wemake-vue-template/builds/302366527?utm_source=github_status&utm_medium=notification

And for some reason `vue-template-compiler` bump is not listed in the pull requests.

**Comment by greysteil** [comment]
Ah, interesting. Is there any way Dependabot could have known that in advance (short of hardcoding info like this about vue)? In future I'd like Dependabot to support yarn's `resolutions`, but it doesn't yet.

For that repo, the `vue-template-compiler` PR will not have been created as Dependabot will have reached its maximum number of PRs (5) for a new repo. If you click to run another update job, it'll probably be created in the next batch.

**Comment by sobolevn** [comment]
@greysteil wow, that interesting. I did not know about that limit. 
In this case, how does dependabot sorts these pull request? Because there are minor bug fixes, security updates, new major version, etc.

**Comment by sobolevn** [comment]
@greysteil sorry for some many issues!

**Comment by greysteil** [comment]
They're sorted randomly, since it's just meant to be a temporary measure while people get a repo up-to-date. Once Dependabot has made an update run that needed fewer than 5 dependencies updating it moves into ongoing-maintenance mode, where it will create as many PRs as it needs each time it runs (normally fewer than 5 anyway).

I'll reply to the security question on the separate issue you created.
