### ISSUE TITLE
Run security checks

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#46]
I don't know if that already implemented, by I want to be sure that dependencies provided by `dependabot` are secure.

What is possible to do about it?
1. Check existing dependencies with static analyzer 
2. Check suggested dependecies to be secure
3. Create issues even if there is unsafe dependency with no possible upgrade

There are tools for that in all languages:
- `safety` for `python`
- `nsp` for `node`

And so on.

**Comment by greysteil** [comment]
This would be quite a nice feature, but we haven't added it yet for a couple of reasons:
- Being on the latest dependency is basically always the most secure strategy. We did some research on it [here](https://dependabot.com/blog/the-latest-dependency-version-is-probably-the-most-secure). As a result, it's extremely unlikely you'd ever want to skip an update
- We don't like doing things badly, and doing this well would be a *lot* of work. In particular, we'd really like to see a resurrection of the OSVDB in order to do this well. Dependabot doesn't make enough money to pay either of the developers who work on it yet, but if/when it does we'd like to use that money to pay a salary for someone to work full-time on building a new version of the OSVDB. (We *hate* the strategy a few security firms have taken recently of curating their own, private list of security vulnerabilities.)

We almost certainly will add this at some point, but it's such a big feature I don't think it belongs in issues - it's just going to sit here and oppress me, so I'm going to close. I definitely hear you, though!

**Comment by sobolevn** [comment]
https://github.com/blog/2470-introducing-security-alerts-on-github
