### ISSUE TITLE
Respect bundler configuration.

### ISSUE THREAD

**Issue by r-plus** [dependabot/feedback#480]
We are using gem from github latest commit instead of version like this Gemfile.

### Gemfile

```
source "https://rubygems.org"

gem 'github_changelog_generator', :github => 'github-changelog-generator/github-changelog-generator'
```

### Gemfile.lock

```
GIT
  remote: https://github.com/github-changelog-generator/github-changelog-generator.git
  revision: 9e0a9592529d09591778722d17e82ce896e4a0b7

...
```

and we are using https protocol instead of git protocol by this bundler configuration.

### .bundle/config

```
---
BUNDLE_GITHUB__HTTPS: "true"
```

In that repository, dependabot create pull request for update github-changelog-generator gem that changed to git protocol from https protocol like below diff.

```diff
GIT
-  remote: https://github.com/github-changelog-generator/github-changelog-generator.git
-  revision: eb53343befc84ae34e006984d086dd14b7b53c7f
+  remote: git://github.com/github-changelog-generator/github-changelog-generator.git
+  revision: 9e0a9592529d09591778722d17e82ce896e4a0b7
```

We want to respect bundler configuration to use https protocol.

**Comment by greysteil** [comment]
Oh, interesting. This is kind of tricky as I'm guessing you don't commit your `.bundle/config`, so Dependabot needs to reverse engineer it.

The official Bundler recommendation on this one is to include `git_source(:github) { |name| "https://github.com/#{name}.git" }` near the top of your Gemfile (there's discussion [here](https://github.com/bundler/bundler/issues/4978)). Would you be up for doing that? Since that's best practice I'd rather avoid the additional complexity in Dependabot.

**Comment by r-plus** [comment]
Thanks for your response and nice suggestion.
I'll use it for this instead of `.bundle/config`.
