### ISSUE TITLE
Cannot delete my account

### ISSUE THREAD

**Issue by thomasdarde** [dependabot/feedback#488]
Hello,

Where is the link to delete an account ? (not a project)

Thank you

**Comment by greysteil** [comment]
Hi Thomas,

You can uninstall Dependabot from your GitHub settings. If you’d like us to delete all data on the Dependabot side we can do that for you, too, but uninstall has to be done from within GitHub.

Grey

**Comment by thomasdarde** [comment]
When will this be accessible via the interface?

**Comment by greysteil** [comment]
We'd need [this endpoint](https://developer.github.com/v3/apps/#delete-an-installation) to be accessible by apps, which it isn't, to make deleting an account possible from within the Dependabot UI. Since that UI is going away anyway (as we fully integrate into GitHub), and this is the first request we've ever received to delete an account, we'll probably continue to process manually during the transition.

**Comment by thomasdarde** [comment]
Clear, thank you for the update
