### ISSUE TITLE
Differing PR names.

### ISSUE THREAD

**Issue by dotconnor** [dependabot/feedback#494]
I currently use Dependabot on a lot of my projects, however, I have run into some inconsistencies. PR names while consistent for a project different between projects. Some of them include a conventional commit style PR name, e.g. [`chore(deps): bump file-type from 11.0.0 to 11.1.0`](https://github.com/a1motion/reware/pull/50), while others just have a basic PR name: [`Bump tslint from 5.16.0 to 5.17.0`](https://github.com/a1motion/defer/pull/18/files).

How is it determined to used one over the other, and how could I set a preference to use one.

**Comment by greysteil** [comment]
The logic on this is quite complicated, and is [here](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/message_builder.rb#L171-L184). Basically, Dependabot looks at your existing commits to try to figure out if you're using semantic commits, and follows that approach if you are. If you're not, it uses a most human-readable format.

There isn't currently a way to configure the above, but since it's a common request we're likely to add it as we integrate fully with GitHub.
