### ISSUE TITLE
Different PR titles

### ISSUE THREAD

**Issue by amio** [dependabot/feedback#502]
I see two different title format, from same @dependabot-preview, just curious, what caused the difference?

![image](https://user-images.githubusercontent.com/215282/58927707-3bc86d80-8782-11e9-993f-638d992cd0de.png)

- https://github.com/amio/nls/pull/46
- https://github.com/amio/npm-why/pull/45

**Comment by greysteil** [comment]
We try to pick the commit message style that matches your repo, based on your last 100 or so commits. If more than 50% of those are using semantic commits we'll use that, otherwise we'll use a more human-readable style. If you change the commit message (using squash and merge when merging a PR) to a different style then Dependabot will use that new style in future.
