### ISSUE TITLE
no .ruby_version file?

### ISSUE THREAD

**Issue by YellowstoneApps** [dependabot/feedback#504]
Dependabot encountered this issue:

```
Bundler::Dsl::DSLError with message: 
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - .ruby_version. Bundler cannot continue.
```

because my Gemfile has:  `ruby File.read('.ruby_version').chomp`

`.ruby_version` does in fact exist and every other tool plays nice with it.  Why can't dependabot see it?

It is not .gitignored.  It is definitely tracked.

**Comment by greysteil** [comment]
Hmmm, Dependabot normally does fetch the ruby version file (you can see the logic [here](https://github.com/dependabot/dependabot-core/blob/master/bundler/lib/dependabot/bundler/file_fetcher.rb)). Can you ping Dependabot from the issue, so that we can debug it from there? It makes it a lot easier as we'll then be able to replicate it and dig into exactly what's happened.
