### ISSUE TITLE
Later version superseded by an earlier one

### ISSUE THREAD

**Issue by davidgruar** [dependabot/feedback#506]
[Axios](https://github.com/axios/axios/releases) recently released v0.19.0, followed a couple of days later with v0.18.1. (The motivation for the latter was presumably to push out a security fix to users unwilling to upgrade to a version with potentially breaking changes.)

Dependabot duly opened a PR to upgrade to 0.19.0, but subsequently closed it and opened a PR for 0.18.1. This is despite the fact that 0.19.0 is listed as the latest version on [npmjs.com](https://www.npmjs.com/package/axios).

Is this intentional behaviour? I would prefer later versions (according to semver) to take precedence over earlier ones, regardless of when they were published.

**Comment by greysteil** [comment]
This is a special case because 0.18.1 and 0.19.0 are both security updates. Dependabot tries to update you to the minimal fixed version when addressing a security vulnerability, so it prefers the 0.18.1 release. Because the 0.18.1 release came out *after* the 0.19.0 release you see this counterintuitive behaviour, but I think it *is* desirable in most cases.

What we could do better here is the communication. Dependabot should explain why it has done this superseding for this case, and perhaps keep the original pull request open, too.

**Comment by davidgruar** [comment]
Thanks - that makes sense. Some extra info on the PR, and/or keeping the original PR open, would be great.
