### ISSUE TITLE
Branch.io is referred to as 'library' in PR title

### ISSUE THREAD

**Issue by TylerCarberry** [dependabot/feedback#513]
Dependabot made a PR with the title "Bump library from 2.17.1 to 3.2.0"

It's not that big of an issue and it's branch's fault for naming their dependency 'library'. Just wondering if there's an easy fix.

Changed lines:
`implementation 'io.branch.sdk.android:library:2.17.1'` was changed to `implementation 'io.branch.sdk.android:library:3.2.0'`

**Comment by RohanNagar** [comment]
I have a similar issue with the AWS Java SDK (for Maven). I use the bom in order to pull in version information for all of the AWS SDK packages, so it's a little confusing when the PR title says `Bump bom from 2.5.51 to 2.5.54`

Example PR: https://github.com/RohanNagar/thunder/pull/480
Dependency reference: https://github.com/RohanNagar/thunder/blob/master/pom.xml#L378-L384

I actually prefer just using the artifact name in the PR title as it usually makes it more clear, it's just these weird edge cases. Not sure if you can/want to do anything in Dependabot to special case these.

**Comment by greysteil** [comment]
I think the only option here is to special case, so let's do that. I'll create a PR :-)

**Comment by greysteil** [comment]
Proposed fix over at https://github.com/dependabot/dependabot-core/pull/1203.

**Comment by RohanNagar** [comment]
The fix looks great 😄

https://github.com/RohanNagar/thunder/pull/485
