### ISSUE TITLE
JavaScript: Don't update major version

### ISSUE THREAD

**Issue by umanghome** [dependabot/feedback#514]
Is there a way in the config that I can ask Dependabot not to update major versions? If we're using 1.x.x and Dependabot wants to upgrade to 2.x.x, it's not really feasible since there might be a lot of breaking changes.

Not sure if I'm supposed to be looking at [these docs](https://dependabot.com/docs/config-file/#version_requirement_updates). If I am, they are extremely unclear.

**Comment by umanghome** [comment]
I can do this with by commenting `@dependabot ignore this major version` on the PR, but that is manual and I'd have to do it for multiple packages. I'd really appreciate if there was a config to specify this behavior with.

**Comment by feelepxyz** [comment]
@umanghome sorry for not being clearer in the docs! We don't have a straight forward way to ignore all major versions atm. I would recommend using config files and [explicitly ignoring](https://dependabot.com/docs/config-file/#ignored_updates) new major versions of the packages you know will be painful to upgrade to.

If you would rather ignore all major versions you can achieve something close to this with `version_requirement_updates` set to `off` - this will only update the lockfile to any new versions that are allowed by the version requirement in your manifest (e.g. `package.json`). You'll need to update your manifest requirements to allow all versions if the current major version to make sure you don't miss any minor/patch versions.

For example using npm, with `version_requirement_updates: off` and your package.json looking like this:

```json
{
  "dependencies": {
    "lodash": "^1.0.0"
  }
}
```

You would only get versions for `1.x`, ignoring `>= 2.x`.

It's not ideal because it requires you check all your version requirements and know what versions will be installed and also manually check for any major versions when you want to upgrade as Dependabot won't tell you about them.

**Comment by greysteil** [comment]
Closing this as answered
