### ISSUE TITLE
Feature Request: Enable Squash and Merge for Automatic Merging

### ISSUE THREAD

**Issue by TimonGaebelein** [dependabot/feedback#533]
The whole auto merging feature is just awesome and proofs to be working very nicely! One thing, that bugs me however, is, that the PR is merged, rather than squashed and merged. I, personally, like it better, if there is only a single commit in the master commit history for a dependency update.

Because you've already added the functionality as a command, I was thinking, whether it would be possible to have squash and merge be configurable for auto merging, as well?

**Comment by greysteil** [comment]
It's possible! It's configured at the account level, rather than the repo level, at the moment, but if you got to your Dependabot account settings you'll see the following options:

![image](https://user-images.githubusercontent.com/1144873/59681626-34915e80-9189-11e9-9683-3034032b6bcc.png)

We'll move this down to the repo level soon.

**Comment by TimonGaebelein** [comment]
Totally forgot to look at the account level! Thanks!

**Comment by PetterSa** [comment]
Nice! I was looking for this as well. So I have to uncheck `Create a merge commit if a PR is merged by Dependabot` in order for it to do an automatic squash and merge?

**Comment by greysteil** [comment]
Yep!

**Comment by marcaddeo** [comment]
@greysteil these are my settings in my Dependabot account:

![image](https://user-images.githubusercontent.com/199649/69667637-6245d200-105c-11ea-8c6c-7297449293d8.png)

However, when I approve the PR Dependabot does not squash the commits and only merges them into `master`.

![image](https://user-images.githubusercontent.com/199649/69667734-8f928000-105c-11ea-97c6-7bec0ad371ec.png)

For some context: we have a bot that automatically updates our CHANGELOG when Dependabot bumps things. The bot makes a second commit so that Depedabot (shouldn't) have issues rebasing when the lock file changes. The behavior I'd like to see if when I approve the PR, Dependabot does a squash and merge.

It seems like that behavior is supposed to work. Am I doing something wrong?

Thanks

**Comment by greysteil** [comment]
Interesting. I'm not close to this anymore (Dependabot is with another team at GitHub) but this is likely because Dependabot uses rebase merges, not squash merges, when asked not to create merge commits. That seems like generally the correct thing for Dependabot to do, so we'd have to add an additional option to support your use case, or perhaps you could use mergify.io?
