### ISSUE TITLE
1.0.0.RC9.2 newer than 1.0.0-RC14

### ISSUE THREAD

**Issue by robstoll** [dependabot/feedback#582]
the problem is due to the changed version schema. See https://github.com/robstoll/kbox/pull/2

**Comment by greysteil** [comment]
This one is tough - there's a very clear specification of how version ordering works [here](https://maven.apache.org/pom.html#Version_Order_Specification) which is what Dependabot uses for Maven and Gradle. I can see how that's confusing here, but I don't think we can move away from it - the problem here is with the library author I think.

**Comment by robstoll** [comment]
Good to know, I think you implemented the specification wrong though:
Splitting and replacing results in:
1.0.0.RC-9.2
1.0.0-RC-14

if the prefix is the same, then compare the token [...] => means above it can compare 1.0.0 which is equal for both. Then...
else ".qualifier" < "-qualifier" < "-number" < ".number"  => `.RC` < `-RC` which means 1.0.0-RC.. should still be considered to be newer than 1.0.0.RC...
No?

**Comment by greysteil** [comment]
Not quite - before prefix comparison comes the trimming of null values. In that step `1.0.0.RC-9.2` -> `1.0.0.RC-9.2` but `1.0.0-RC-14` becomes `1-RC-14`.

**Comment by robstoll** [comment]
I see, thanks for clearing that up and I agree that it is mainly a problem of the library author.
