### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by Chronyms** [dependabot/feedback#59]
I would like tho have bower support.
This should have some similliarity to npm and yarn, just with different file-names.

Tank you

**Comment by greysteil** [comment]
Thanks for the feedback!

We've held back on adding Bower support since [Adam  himself is recommending users switch to Yarn](https://bower.io/blog/2017/how-to-migrate-away-from-bower/). Whilst we could do it, realistically it's not likely to be a high priority in the near future, unless I'm missing something?

**Comment by ChristophWurst** [comment]
FYI bower has been deprecated for a while now: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#383
