### ISSUE TITLE
Issue connecting to Dependabot with Enterprise Acct

### ISSUE THREAD

**Issue by nsorner** [dependabot/feedback#590]
Issue connecting to Dependabot with Enterprise Acct. We have personal and enterprise accounts. Dependabot asked me which acct I wanted to use, I selected the enterprise acct. Then when I tried to install it wanted to connect to my personal account and then I got an error.

**Comment by greysteil** [comment]
Thanks for getting in touch. Do you mean a GitHub Enterprise Server account? I'm not really sure what's happening from the description above - any chance you could upload screenshots of the flow so I can debug where things are going wrong?

**Comment by dhavalp2010** [comment]
Hi... greysteil -- We are really excited to see dependbot on our Enterprise GitHub setup.
Based on your above comment do you mean there there is no way currently to integrate dependbot in Enterprise GitHub (onpremise enterprise github)?

**Comment by greysteil** [comment]
We want to have full GitHub Enterprise Server support in the next 12 months (it's a tricky project because Dependabot works by spinning up environments that are safe for remote code execution.  We need to  build the infrastructure for that to be possible in GHE).

In the meantime you can use [Dependabot Script](https://github.com/dependabot/dependabot-script) to run a very lightweight version of Dependabot locally and follow [this issue](https://github.com/dependabot/feedback/issues/485) for updates. :octocat:
