### ISSUE TITLE
Overwhelmed by number of PRs opened

### ISSUE THREAD

**Issue by fent** [dependabot/feedback#595]
Hi, I just installed dependabot, and got alerted for several PRs, around 70, for updating dependencies. Looking through them, many of them of them only change the lockfile (`package-lock.json`) without changing the main dependency list file (`package.json`). This is expected?

I've used greenkeeper before, and it would only create a PR if the new version didn't match the version in `package.json`. But the PRs that dependabot made, are all for minor or patch updates that should already match in `package.json`. I think that I would rather have updates only for major versions, specially for packages in `devDependencies`.

Another thing with `devDependencies`. I have a number of libraries that use the same or similar `devDependencies`. Whenever there's an update for mocha for example, I'm going to get several emails, one for each of of the libraries that use mocha.

I guess I'm just wondering if this is expected behavior? Overall, I'm feeling like dependency maintenance is now going to be more work. And I'm wondering if projects that are currently in maintenance mode should even have their dependencies updated for non-security reasons, and for minor/patch versions, and for dev dependencies.

**Comment by greysteil** [comment]
Thanks for the comment @fent.

Greenkeeper is quite a different service to Dependabot, which I think it probably the source of the confusion here. Specifically, Dependabot is mainly targeted towards applications, rather than libraries.

With an application you almost certainly *do* want all the patch and minor releases that might only affect your lockfile. That's what Dependabot provides.

With a library, on the other hand, you sometimes want the above behaviour but it's not uncommon to only want to hear about new versions that fall outside of your allowed version range or about updates that are in your allowed version range but break your build. That's the functionality Greenkeeper provides, and Dependabot doesn't currently try to compete with them there (we've always been big fans of their approach).

So for now, my answer on this one is that it sounds like you need Greenkeeper for your libraries, rather than Dependabot! We may add a configuration option to make Dependabot act like Greenkeeper at some point (if it's ever needed).

Hope that helps?

**Comment by fent** [comment]
Ok, that helps a lot, thank you! I was going to disable my greenkeeper, but from this I gather I should keep both around. I'm going to keep using dependabot in libraries for security updates, since greenkeeper doesn't handle those.

Actually, how does dependabot compare to snyk?


> That's the functionality Greenkeeper provides, and Dependabot doesn't currently try to compete with them there (we've always been big fans of their approach).

As a user, I would prefer to have use only one app so I can configure everything from one place. If dependabot wants to be like greenkeeper, one way to do that is to add a filter

![Screen Shot 2019-07-26 at 11 56 57 PM](https://user-images.githubusercontent.com/933490/61989700-53450980-b001-11e9-9867-bc70c63779f6.png)

something like the inverse of only lockfile changes, "only package.json changes"


Thank you for the help, and for dependabot.
