### ISSUE TITLE
Not a single PR since adding Dependabot

### ISSUE THREAD

**Issue by web2033** [dependabot/feedback#608]
"Bump now" doesn't help either.

**Comment by greysteil** [comment]
What's the full name of the repository this is happening on?

**Comment by web2033** [comment]
https://github.com/web2033/webpack-starter

**Comment by greysteil** [comment]
Looks like all of the version ranges you have specified on that repo support the latest version, and you don't have a lockfile on it. What PRs were you expecting Dependabot to generate? If you want Dependabot to update your `package.json` so that the ranges in it are bumped (even though they already support the new versions) you can set that preference on the update config from your Dependabot dashboard.

**Comment by web2033** [comment]
Ok, I'll try it, thanks
