### ISSUE TITLE
Additional npm dependency bumped unexpectedly

### ISSUE THREAD

**Issue by RDIL** [dependabot/feedback#610]
In https://github.com/RDIL/cirrus-ci-web/pulls , all dependabots PRs include the exact same diff

**Comment by greysteil** [comment]
Can you say more on this? The diffs on [this](https://github.com/RDIL/cirrus-ci-web/pull/6) and [this](https://github.com/RDIL/cirrus-ci-web/pull/8) are not the same. Is there something it's messing up consistently?

**Comment by RDIL** [comment]
It mumped material ui even though it had a different PR for it

**Comment by greysteil** [comment]
Yeah, looking at https://github.com/RDIL/cirrus-ci-web/pull/2/files something definitely isn't right - I can't see why Dependabot would be quietly bumping that dependency at the same time there.

This is one for @feelepxyz to dig into when he's back from holiday - thanks for flagging it.

**Comment by feelepxyz** [comment]
Taking a look now!

**Comment by feelepxyz** [comment]
@RDIL I think this is expected due to the loose requirements in your package.json, specifically npm seems to always update packages with the `latest` requirement when updating any other package.

If you specify the version requirement in your `package.json` you won't get this behaviour, tested here https://github.com/feelepxyz/cirrus-ci-web/commit/7b7e5c85cd5bc3ba9df492ff60b02db411ac3054 - which resulted in this PR being created: https://github.com/feelepxyz/cirrus-ci-web/pull/12

**Comment by feelepxyz** [comment]
@RDIL oh seems only `latest` behaves like this so you could also change to `*` on the `@material-ui` dependencies and fix this issue.

**Comment by greysteil** [comment]
Oh interesting! @feelepxyz reckon we should replace `latest` with `*` when prepping the manifest files for update so as to avoid this on our side?

**Comment by feelepxyz** [comment]
@greysteil good shout! Will have a go at doing that.
