### ISSUE TITLE
Support vendoring for PHP

### ISSUE THREAD

**Issue by ChristophWurst** [dependabot/feedback#62]
Hi there,

I just wanted to give dependabot a test run for [Nextcloud's 3rdparty libs](https://github.com/nextcloud/3rdparty/issues/36#issuecomment-351308076) and I've encountered a problem. Instead of pulling dependencies every time, we do commit them in our git repo. However, dependabot seems to only update the `composer.json` and `composer.lock` file. The actual source files of the updated dependencies remain outdated.

Is there any way to tell dependabot to commit those changes?

Note: since it's just a test, I tried to enable it on [a fork](https://github.com/ChristophWurst/3rdparty) first to see how well it works. As you can see [here](https://github.com/ChristophWurst/3rdparty/pulls), it correctly detected outdated libs, but none of the source files were changed in those PRs.

Thanks

**Comment by greysteil** [comment]
Ah, interesting. Dependabot doesn't support vendoring for any of the languages it updates at the moment, but it's on the list of things I'd like to support. I'm going to extend the title of #15 to include PHP, since the work to do so will essentially be the same.

This is quite a big project (probably a couple of days work on [Dependabot Core](https://github.com/dependabot/dependabot-core)) so I can't promise we'll add support immediately, but I do definitely want to get to it.

**Comment by ChristophWurst** [comment]
Thanks a lot, @greysteil!

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#386
