### ISSUE TITLE
Auto-merge seems flaky

### ISSUE THREAD

**Issue by JayH5** [dependabot/feedback#63]
Hi there 👋

We use Dependabot to keep some Python requirements files up-to-date for [this repo](https://github.com/praekeltfoundation/debian-wheel-mirror). We have auto-merge switched on for all patches.

Sometimes Dependabot will merge its PRs once the build is green, e.g. praekeltfoundation/debian-wheel-mirror#185.

Sometimes it won't and I have to do it manually, e.g. praekeltfoundation/debian-wheel-mirror#186.

I didn't restart any builds for those PRs or anything (and IME when I do, Dependabot sometimes does/does not merge the PR).

Thank you for the very useful tool 🙏

**Comment by greysteil** [comment]
Hi @JayH5, and thanks for the kind words!

We generally include a reason in the PR description if, for some reason, Dependabot isn't going to automerge a PR. In the case of praekeltfoundation/debian-wheel-mirror#186 it looks like the cause was that that dependency follows CalVer, not SemVer, and so there's this line in the PR description:

> Dependabot will not automatically merge this PR because this dependency doesn't follow SemVer.

For dependencies that don't follow SemVer there's no guarantee that the author intends the changes to be backwards compatible, so we don't think it's the right thing to do for Dependabot to merge them. In future I might introduce an "all" option to automerging, in which case Dependabot would be able to merge non-SemVer updates, too.

Hopefully that clears things up?

**Comment by JayH5** [comment]
Right... I should learn to read properly, thanks 🤦‍♂️

> In future I might introduce an "all" option to automerging, in which case Dependabot would be able to merge non-SemVer updates, too.

Yes please! In this case we aren't managing requirements for a particular application--all we care about is building packages into wheels. Should I create a separate issue for a feature request?

**Comment by greysteil** [comment]
Nah - I've got a bit of time this morning so I'll just get it done 🙂

**Comment by greysteil** [comment]
OK, you can now select "All updates" as an automerge strategy. Use with care!

![image](https://user-images.githubusercontent.com/1144873/41664328-7cc8ec42-7473-11e8-9e96-2c908fc8d5d0.png)
