### ISSUE TITLE
php repositories without lock file

### ISSUE THREAD

**Issue by yaroslavmo** [dependabot/feedback#631]
Hi dependa bot team. 

My project is on Laravel and separated in a lot of packages. All of the dependency packages don't have composer.lock file (only main package has it). It looks like dependabot ignores those repositories. 

For example, I create a new release in one package and need to bump its version in all dependant packages. I thought dependabot will help me with this but it created only PRs in the repo that has composer.lock file.

**Comment by greysteil** [comment]
Dependabot won't update `composer.json` ranges unless it has to (because generally that's not the behaviour folks want), but you can configure that behaviour. Just click the cog next to the update config in your dashboard (or from in a config file). If you do so you should be able to get the updates you want.

**Comment by yaroslavmo** [comment]
@greysteil You mean "Update strategy for composer.json" section? I have tried all three of the options, none of them triggered a PR https://img.in6k.com/screens/3b105576_2019.14.08.png

**Comment by greysteil** [comment]
What's the repo? I can try to help you debug it?

(I would use the "Increase versions (always)" options from that list.)

**Comment by yaroslavmo** [comment]
https://github.com/dreamfactorysoftware/df-azure

and the package that has new version is https://packagist.org/packages/dreamfactory/df-database

**Comment by greysteil** [comment]
Hmmm, that does look like a bug on our side - I'll take a look.

**Comment by yaroslavmo** [comment]
Ok. Thank you! I will not do the bump manually, so you can reproduce it. Let me know if you figure this out.

**Comment by greysteil** [comment]
Did some digging into this one - it looks like Dependabot can't update your dependencies on that repo because it can't resolve them. I tried pulling it down locally, too, and got the same error from Composer:

```
Problem 1
    - dreamfactory/df-core 0.15.1 requires tymon/jwt-auth ~1.0.0 -> satisfiable by tymon/jwt-auth[1.0.0-alpha.2, 1.0.0-alpha.3, 1.0.0-alpha1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 1.0.0-rc.4, 1.0.0-rc.4.1, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
    - dreamfactory/df-file 0.6.3 requires dreamfactory/df-core ~0.15.1 -> satisfiable by dreamfactory/df-core[0.15.1].
    - Installation request for dreamfactory/df-file ~0.6.3 -> satisfiable by dreamfactory/df-file[0.6.3].
```

We've made a change to Dependabot Core that will mean it creates an issue on your repo for cases like this in future, rather than silently failing. The relevant PR is [here](https://github.com/dependabot/dependabot-core/pull/1317).

**Comment by yaroslavmo** [comment]
Thank you a lot!
