### ISSUE TITLE
GitHub-detected security fixes not auto-opened by dependabot

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#654]
GitHub has been notifying me of security vulnerabilities where I can choose to have it open a PR (which is powered by dependabot). Why hasn't dependabot already opened that PR? 

and maybe not the right place for this question: is there anyway to configure GitHub to automatically open security PRs for all repos, or do I have to go through one at a time?

**Comment by greysteil** [comment]
Slightly tricky to debug this one. Do you have automated security fixes turned on on those repos? You won't get PRs automatically otherwise - you'll have to click a button to create them.

There's no way to  turn automated security fixes on org-wide at  the moment, but we're planning to  add it. In the meantime there *is* an API  for enabling it at the repo level.

**Comment by greysteil** [comment]
Ah cool. There's an added complexity that there are some vulnerabilities (WhiteSource ones) that Dependabot Preview doesn't have access to. Perhaps this was one of them?

**Comment by ianwremmel** [comment]
maybe. I guess I was more confused that dependabot didn't see it as a normal "there's a new package out so let's open a pr scenario".

**Comment by ianwremmel** [comment]
I *think* these were top level dependencies, but I've been dealing with so many security things in various context the last few days, I've lost track.

**Comment by greysteil** [comment]
I know the feeling!
