### ISSUE TITLE
Change logs from inside npm packages

### ISSUE THREAD

**Issue by xt0rted** [dependabot/feedback#662]
When an npm package is part of a mono repo, such as [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base), the PR comment doesn't include a change log (see https://github.com/xt0rted/eslint-action/pull/6). Since the package includes the `CHANGELOG.md` that's in their repo, would it be possible to pull the contents from there?

**Comment by feelepxyz** [comment]
@xt0rted yeah we'll need the package.json for each package to include the repo directory, otherwise there's no easy way to determine where to look for the changelog.

It's a pretty straight forward change, if you're keen to PR the change to `airbnb/javascript`. Here's an example how it's done for react: https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/package.json#L5-L9
