### ISSUE TITLE
Not all Python Dependency Files Updated

### ISSUE THREAD

**Issue by jamescurtin** [dependabot/feedback#673]
**Issue Summary**: Dependabot PRs only update `Pipfile`, though there are other Python requirements files in the repository.

**Details**: The repo [cookiecutter-flask](https://github.com/cookiecutter-flask/cookiecutter-flask) contains both a `Pipfile` and requirements files (`requirements/dev.txt` and `requirements/prod.txt`). The correct files seem to be monitored by Dependabot (screenshot below). Here is an example of a [Dependabot commit](https://github.com/cookiecutter-flask/cookiecutter-flask/commit/d5d365b3970c077953f0a26bd4f4e28ff6e9bbbd) where the `Pipfile` was updated, but [`requirements/prod.txt`](https://github.com/cookiecutter-flask/cookiecutter-flask/blob/dependabot/pip/%7B%7Bcookiecutter.app_name%7D%7D/sqlalchemy-1.3.8/%7B%7Bcookiecutter.app_name%7D%7D/requirements/prod.txt#L10) was not

![image](https://user-images.githubusercontent.com/10189269/64913041-a7699180-d706-11e9-85b1-6534888b6fbc.png)

Thank you!

**Comment by feelepxyz** [comment]
@jamescurtin thanks for reporting! You'll need to add the `requirements` folder explicitly to have Dependabot update `dev.txt` and `prod.txt`, they are currently only included in the list of monitored files because they are referenced from the top level `requirements.txt` and needed too resolve the file.

You should be able to fix this by adding a new language/directory to the [cookiecutter-flask](https://github.com/cookiecutter-flask/cookiecutter-flask) repo from your [Dependabot dashboard account](https://app.dependabot.com/accounts/cookiecutter-flask) with the directory set to: `/{{cookiecutter.app_name}}/requirements/`

**Comment by feelepxyz** [comment]
@jamescurtin just clarifying, this only happens when the same dependency exits in a requirements.txt and a Pipenv/Poetry file which is case for you.

**Comment by jamescurtin** [comment]
Thanks for the clarification, and appreciate the assistance! This has resolved the issue.
