### ISSUE TITLE
Please stop spamming me.

### ISSUE THREAD

**Issue by mason-bially** [dependabot/feedback#676]
Why are you spamming [my 3 year old repository](https://github.com/mason-bially/relicrunner) I am merely keeping up for posterity's sake [with pull requests](https://github.com/mason-bially/relicrunner/pulls?q=is%3Apr+author%3Aapp%2Fdependabot). Are all of the one off projects I've done over the years going to get spammed every time a new security vulnerability is released? Use an opt-in model, don't make the norm be spam first. Also, how do I opt-out in general since I can't block your app.

Please stop. Please use opt-in instead of opt-out.

**Comment by greysteil** [comment]
Hi Mason,

I presume this is for GitHub Automated Security Fixes - you'll automatically get PRs to fix any vulnerabilities you have, if you're receiving security alerts on that reason.

You can disable Automated Security Fixes on your personal account from https://github.com/settings/security (see the "Automated security fixes" heading) or from https://github.com/organizations/<your-organisation>/settings/security for organisation accounts.

GitHub will continue to roll out automated security fix PRs for all repos that are receiving vulnerability alerts (which you can also opt out of at a per-repo level, or by archiving a repo) because we want to make it easy for folks to fix the vulnerabilities we alert them of.
