### ISSUE TITLE
dependency either not detected or new version ignored

### ISSUE THREAD

**Issue by robstoll** [dependabot/feedback#698]
I have a gradle project where a dependency to another project is kind of hidden in code. Therefore I have created an additional configuration named `dependabot` to help dependenabot out: 
https://github.com/robstoll/tutteli-gradle-plugins/blob/master/build.gradle#L23

It seemed to work for some time but now it does not any more (or it never did and I only thought it helped). for instance, [spek](https://bintray.com/spekframework/spek/spek2) has a newer 2.0.7

**Comment by rebelagentm** [comment]
👋 There is indeed an issue here.  Our file parser was picking up the `$project.spek_version` from [line 198](https://github.com/robstoll/tutteli-gradle-plugins/blob/master/build.gradle#L198) and replacing the actual version number from earlier in the file.  It did the same for the `junit` dependency.  Interestingly, it didn't have this problem with `jacoco` because you named the variable slightly different, i.e. `jacoco_toolsVersion` instead of `jacoco_toolVersion`. 😄 

We're working on a fix right now.  Thanks for submitting this!

**Comment by rebelagentm** [comment]
This should be fixed in https://github.com/dependabot/dependabot-core/pull/1481.
