### ISSUE TITLE
NPM packages pre-release versions not updated 

### ISSUE THREAD

**Issue by oliverfernandez** [dependabot/feedback#701]
Not sure if this is a bug or an unsupported feature

SemVer pre-release versions like `1.0.0-snapshot.1 < 1.0.0-snapshot.2 < 1.0.0-snapshot.3` are not detected and updated by Dependabot

You have an example in the following repository: https://github.com/oliverfernandez/marfeel-tenant

If you take a look at the `package-lock.json` of that repository 
- The dependency `@oliverfernandez/marfeel-core-release` is resolved against the version `1.0.0-snapshot.1`
- But the current version of that package is `1.0.0-snapshot.3` (it's published here: https://github.com/oliverfernandez/marfeel-core-release/packages/24167)

If I do a manual `npm update` in my machine, `npm` is correctly installing the new version, and it changes the `package-lock.json` to `@oliverfernandez/marfeel-core-release/1.0.0-snapshot.3`, but when I tell Dependabot to bump versions, it is not triggering the update

 My use case is that I have a project that works "per-commit release", and working with "spanshots" versions is the best way to publish the package every time there's a commit in the `master` branch of the repository, without having to generate a second commit updating the `package.json` version itself

**Comment by rebelagentm** [comment]
Hi!  Thank you for submitting this.  The team is heads down scaling Dependabot for all of GitHub :octocat:, but we'll take a look at this as soon as we can.

**Comment by feelepxyz** [comment]
@oliverfernandez @rebelagentm this might be an easy one to fix, looks like we should be supporting this syntax from the looks of this: https://github.com/npm/node-semver#prerelease-tags

Could start by adding some tests here checking this syntax gets detected as a `prerelease?`: https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/spec/dependabot/npm_and_yarn/version_spec.rb

**Comment by rebelagentm** [comment]
@oliverfernandez There does seem to be an issue in Dependabot picking up this dependency.  @feelepxyz and I are looking into it.

**Comment by feelepxyz** [comment]
@oliverfernandez figured this out and this is caused by the fact that you have released a version `1.0.11` which compares as newer than `1.0.0-snapshot.3` so we try to update to this version but this update has already been attempted and closed. Could you change this prerelease version to something like `1.1.0-snapshot.3`?

**Comment by oliverfernandez** [comment]
Sorry for my delayed response.

@feelepxyz @rebelagentm  I did as you said, and changed to version `1.1.0-snapshot.3` and later to `1.2.0-snapshot.6` and Dependabot is still not picking up the change

**Comment by feelepxyz** [comment]
@oliverfernandez oh sorry missed this in our logic, we only update update to a pre-release if it's related to the current pre-release version. So we won't update to `1.2.0-snapshot.6` because you're currently on `1.0.0-x` and need to be on `1.2.0-x`. Pretty sure this will work if you change the version manually on master to `1.2.0-snapshot.6` and then keep pushing pre-releases on `1.2.0-x`. Sorry for the confusion. We have this logic in place as most users don't want us to update them to the latest pre-releases.

**Comment by oliverfernandez** [comment]
@feelepxyz Yes! That worked! https://github.com/oliverfernandez/marfeel-tenant/pull/26

Thank you very much for all your help! :)

**Comment by feelepxyz** [comment]
@oliverfernandez nice one!
