### ISSUE TITLE
Documentation on the behavior of widen_ranges

### ISSUE THREAD

**Issue by frangio** [dependabot/feedback#707]
I would like to know precisely what `widen_ranges` is supposed to do, and I haven't been able to find a description.

**Comment by feelepxyz** [comment]
@frangio thanks for asking, we can definitely do a better job explaining it. We have the config option documented here: https://dependabot.com/docs/config-file/#available-update-strategies

Usually you'd want to use `widen_ranges` for libraries that are published on a package registry to allow for broader ranges to be installed. Dependabot will try to update the version requirement so that the current versions + the new ones can be installed with the updated version requirement.

If you don't set `version_requirement_updates` Dependabot will use `widen_ranges` when we don't detect a lockfile for python and npm/yarn (`increase_versions_if_necessary` for cargo, composer and bundler), and when a lockfile is detected `increase_versions` is used.
