### ISSUE TITLE
When defining multiple package managers, only the last is respected

### ISSUE THREAD

**Issue by malliapi** [dependabot/feedback#728]
Given an example of  

`version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    default_labels:
      - 'Mono Repo Dependencies'
      - 'High Priority'
    update_schedule: 'live'
    allowed_updates:
      - match:
          update_type: 'security'
      - match:
          dependency_name: '@storybook/*'
    version_requirement_updates: 'auto'

  - package_manager: 'javascript'
    directory: '/'
    default_labels:
      - 'Mono Repo Dependencies'
    update_schedule: 'weekly'
    ignored_updates:
      - match:
          dependency_name: '@storybook/*'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
      - match:
          dependency_type: 'all'
          update_type: 'semver:patch'
    version_requirement_updates: 'auto'`

only the last package manager is respected. This means i can't have different schedules for different dependencies?

**Comment by feelepxyz** [comment]
@malliapi thanks for raising this. It's currently not possible to per dependency different update schedules and you can only specify one update config per directory, branch and package manager combo which is why the above won't work. We've got a issue tracking per dependency update schedules here so will close this: https://github.com/dependabot/feedback/issues/433
