### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#75]
This is a big feature. Right now you only support GitHub, which is the biggest open-source community out there. But a lot of developers are using GitLab for private projects.

## Motivation

We ([wemake.services](https://github.com/wemake-services)) host all our open-source project on GitHub. But, most of our software projects are private and hosted on GitLab (both self-hosted and SaaS versions).

While we really enjoy dependency upgrades in our open-source projects, our main projects are still upgraded by hands, which sometimes takes a lot of time.

## Benefits for you

Why should you even consider adding GitLab? There are some key points I want you to consider:

1. GitLab is popular. Here are the usage statics and market share: 
![bitrise-self-hosted-chart](https://user-images.githubusercontent.com/4660275/34914739-d929d7dc-f929-11e7-945f-daf17005a767.png)
2. GitLab is used primarily for private projects, so the would be more paying customers
3. GitLab has CI, so it would be very useful to integrate tests that dependency can be updated

What do you think about this feature?
Do you consider adding new providers except GitHub?

Thanks!

**Comment by greysteil** [comment]
Thanks for the request. This is, indeed, a big one!

I'd love Dependabot to support GitLab (and Bitbucket). Doing so would require:
- Changes to `dependabot-core` to make all classes host-provider agnostic. This should be relatively straightforward - I estimate ~ 1 day's work
- Changes to `dependabot-frontend` to handle auth for GitLab (and Bitbucket), which is ~ 1 day's work
- Changes to `dependabot-backend` to listen to use the GitLab API (when listing repos, asking for CI statuses, etc.) and listen for GitLab webhooks. There are a lot of unknowns here, so I think it's ~ 5 day's work.

Whilst I'd love to promise the above is coming, right now I'm not working on it. Dependabot doesn't make enough to support me working on it in more than my spare time (our revenue numbers are in [this interview](https://www.indiehackers.com/businesses/dependabot)), so I can't justify spending more than a few hours on it a day.

I almost certainly will get to this eventually, but no in the next couple of months. Sorry!

**Comment by cafferata** [comment]
Hi @greysteil, I think the concept of Dependabot is very good. I have not come across it before and I wanted to get started right away. Until I came to the conclusion that there is no Gitlab integration. The consequence? I can not actually test it properly.

I've read your above reaction (and the Indie Hackers blog post), and asked myself: _what would @greysteil need to spend more time on Dependabot?_ Would a promise by X number of Gitlab participants be a good stick? Would it help if, for example, we pay a year in advance so that healthy cash flow arises? We, as JCID, are always willing to pay for tools and I think many of our competitors.

**Comment by greysteil** [comment]
Thanks for these extremely motivating words @cafferata, and apologies for the delay getting back to you.

I've been spending a bit more time on Dependabot over the last few weeks, and adding GitLab support is rising up my priority list. There are a couple of things ahead of it (getting Java support out of beta and fleshing out our security advisory sources), but I should be able to prioritise this soon.

It would help a lot to have a list of companies that would be committed to pay for Dependabot if/when I do the work. Adding GitLab support will be a bunch of up-front work, but it's also likely to increase the maintenance burden for me on Dependabot, and I want to be sure that's worth it.

If your company would be up for paying for a small org / unlimited account on GitLab drop a comment below, and I'll try to get to this a little bit sooner.

**Comment by cafferata** [comment]
>*If your company would be up for paying for a small org / unlimited account on GitLab drop a comment below*

@JCID will start with the first 5 projects and I expect that this is soon too small for our organization, after which we will go to the unlimited account. So, who is next? 👍

**Comment by greysteil** [comment]
There are certainly some open questions on how GitLab will work, but high level I'm thinking:
- Ask for an API key, rather than using OAuth2
   - It doesn't cause problems if individuals leave a team
   - As far as I know it's how other applications do this
- Handle billing from within Dependabot
   - I've asked GitLab previously whether they have any intention to build a marketplace and they've said "no".
   - Will require a Stripe integration and a frontend for switching plan within Dependabot

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#399
