### ISSUE TITLE
Notify endpoint does not appear to be opening PRs / enqueuing run of dependabot while 'Bump now' is working

### ISSUE THREAD

**Issue by ajcann** [dependabot/feedback#756]
Currently attempting to use: https://github.com/dependabot/api-docs#notify-dependabot-of-a-private-dependency-release to kick off PR generation to a private repo upon the release of a new docker image to a private docker registry (GCR). 

When I send:

`curl --verbose -d '{"name":"us.gcr.io/<gcr project name>/workflow-testing", "version":"9.0.2", "package-manager":"docker"}' -H "Content-Type: application/json" -H "Authorization: Personal <GitHub PAT with Repo Access>" -X POST https://api.dependabot.com/release_notifications/private
`
I get a 204 response back (which I believe is expected) though no PR is opened. Selecting 'Bump now' does however pick up the change and open a PR.

Am I missing something re: documentation?

Thank you!

Update: I see that this issue is related to https://github.com/dependabot/feedback/issues/324 re: the docker image however I appear to be having the same issue with 'npm_and_yarn' package-manager for the same repo which is set to 'live'. I can manually hit 'Bump now" and it picks up the update, however hitting the release_notifications/private endpoint does not seem to generate any PRs/dependabot runs.

(I have emailed the specific private repo to dependabot-support@github.com)

**Comment by feelepxyz** [comment]
@ajcann just replied to your email! For reference, Dependabot currently parses Dockerfile dependency names without the prefixed host, so the name would be `<gcr project name>/workflow-testing` instead of `us.gcr.io/<gcr project name>/workflow-testing`. This dependency name has to match the one parsed by Dependabot for the update to work.

I'll dig into this further as we might have some issues with it, especially if it's not working for npm and yarn which should have a 1-to-1 mapping between whats in your manifest and what Dependabot parses the name as.

**Comment by ajcann** [comment]
Thank you @feelepxyz 

Will the endpoint work for Docker given that Docker package manager does not support the 'live' schedule? After reading https://github.com/dependabot/feedback/issues/324 I've come to understand that only package managers that support 'live' will work with the endpoint.

**Comment by feelepxyz** [comment]
@ajcann I've removed the `live` update schedule requirement so this should hopefully now work for Docker 🎉

Let us know if that works for your setup.
