### ISSUE TITLE
Dependabot encounters unknown error in rust multi-crate project

### ISSUE THREAD

**Issue by MikailBag** [dependabot/feedback#774]
At start, Dependabot submitted 10 PRs, but since October 1 (I configured dependabot for monthly updates at first, but some time later switched to weekly) dependabot have not sent any pull requests.
I don't think I have big or binary files in this repository.
Project mainly consists of Rust, and toplevel directory is Cargo workspace.
I don't think it connected to me using Rust nigthly features: if Dependabot fails to parse Cargo.toml, it reports detailed error message instead of just "Unknown error".
Full error text:
```
Error bumping dependencies

Dependabot encountered an unknown error.

We've been notified of the problem, and are working to fix it.
```

Repository: https://github.com/mikailbag/jjs

**Comment by feelepxyz** [comment]
@MikailBag looks like the repository is no longer set up with Dependabot Preview. Have you set it up through the dashboard?

**Comment by MikailBag** [comment]
Here is screenshot from dashboard.

![screenshot](https://user-images.githubusercontent.com/11889433/69737261-25a1d580-1145-11ea-87ec-cd0d505472b3.png)

Repository is activated. 
When I was setting up Dependabot, I did it through dashboard.

**Comment by feelepxyz** [comment]
@MikailBag yes sorry missed it! Looks like we're not dealing with cargo workspaces properly. When running updates we only download the manifest files but to run cargo we need some target files so we write a dummy `main.rs` and lib.rs` in `src`. Because of the `workspace` `src/*` glob Cargo tries to check for `lib.rs/Cargo.toml` which is causing the update to bail. I think we need to write these dummy files in each workspace folder instead of in the root `src` folder when it's a workspace with a glob. Will take a look at this.

**Comment by feelepxyz** [comment]
@MikailBag found a fix for this here: https://github.com/dependabot/dependabot-core/pull/1546 - the new release should be live in a couple of hours or so ✌️
