### ISSUE TITLE
Please allow us to modify the commit message format

### ISSUE THREAD

**Issue by StephanBijzitter** [dependabot/feedback#82]
After this pull request: https://github.com/dependabot/dependabot-core/pull/244

Our commitlint started to fail, since we do have it set up to expect `chore(dependencies): `. It's nice that you cater to the Angular project, but this is a breaking change for us. Now we can modify the commit message when squash merging, but that still leaves every pull request with a red cross.

To take a piece of code from the pull request, we would expect the message to be: `"chore(dependencies): bump business from 1.4.0 to 1.5.0"` (notice the `b` in `bump`, not `B`)

So, please allow us to configure this message to our liking. I'd open up a pull request myself, but I have no experience with Ruby. If you agree this is a wanted feature, but you don't have time for it, I'd love to give it a shot though!

```
input: build: Bump commander from 2.12.2 to 2.13.0
   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
   found 1 problems, 0 warnings
```

**Comment by StephanBijzitter** [comment]
I think the following config to `package.json` would be good:
```
  "dependabot": {
    "conventional": {
      "type": "chore",
      "scope": "dependencies",
      "case": "lower-case"
    }
  }
```
This way the config can differ on a per-branch basis, which makes sure that changes to commit(lint) settings and the config will be kept in sync.

**Comment by greysteil** [comment]
Totally agree this is a wanted feature. I’m on holiday with limited time for the next two weeks, but would love a PR.

I think the right approach here would be to edit [this file](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/message_builder.rb) to detect if “chore(dep...” was previously being used, and use that instead of build if so.

**Comment by greysteil** [comment]
(Adding a confit file would need a lot more work, and I’m not convinced it’s a better approach.)

**Comment by deivid-rodriguez** [comment]
I know this would be definitely more work but projects use lots of different commit message conventions, it'd be nice if dependabot played nice with everyone via configuration.

Ideally I'd like to be able to tell dependabot specifically the template for the commit message I want, like:

```
Bump %{library} from %{original_version} to %{final_version}.
```

**Comment by StephanBijzitter** [comment]
A template would also suit our needs. Haven't had time to look much into this yet, running into a bit of a deadline myself... :-)

**Comment by greysteil** [comment]
Just coming back to this.

@deivid-rodriguez - I've updated the logic in Dependabot core so it won't get confused about whether or not you're using semantic commit prefixes anymore (commit [here](https://github.com/dependabot/dependabot-core/commit/d969cf91429567e578896ed885fc62ba6318aeca)). That should mean that you get the commit message you want (which looks like it's the format Dependabot was already using). Are you all good?

@StephanBijzitter - I've updated Dependabot's commit messages the follow the correct sentence case structure (commit [here](https://github.com/dependabot/dependabot-core/commit/4443c5aa7a3b435b73c97c1c6aacdc4ac36dd772)). How important is using `chore(dependencies)` to you, rather than `build`? I can add some logic to do that if you feel strongly about it :-)

I'm going to hold off on adding config files (we can's just use the `package.json` because we need to support multiple languages) or a setting for this for now.

**Comment by StephanBijzitter** [comment]
It's not important, `build` will pass our linter just fine. It's just the semantics of the word that's a bit iffy for me.

**Comment by deivid-rodriguez** [comment]
@greysteil That's great. If dependabot is smart enough to figure out the style I use, that's of course good enough! :+1:.

**Comment by greysteil** [comment]
Cool, thanks guys. In that case I'm going to close this for now, but I'm happy to revisit later.

@StephanBijzitter - I know what you mean about the semantics, but `build` is what Angular are [using themselves](https://github.com/angular/angular/commits/master/package.json), so think it's the one to go for. (AngularJS is still using `chore`, but I'm going to put in a PR to see whether that's deliberate.)
