### ISSUE TITLE
Dependabot is assigning wrong label to PR's

### ISSUE THREAD

**Issue by Borewit** [dependabot/feedback#846]
Dependabot is assigning the wrong label to PR's:

![image](https://user-images.githubusercontent.com/23255260/73819723-793d3900-47f0-11ea-9dd5-7f26e3a63ef8.png)

I have not changed the original blue "dependencies" label:

![image](https://user-images.githubusercontent.com/23255260/73819812-a8ec4100-47f0-11ea-8fc7-2cf33e60fa51.png)

I have notices this behavior on multiple repositories.

Screenshots originating from: https://github.com/Borewit/strtok3

**Comment by feelepxyz** [comment]
@Borewit oh looks like dependabot has re-used the label as it matches `*dependency*` but should prioritise an existing `dependencies` label. Will take a look.

**Comment by Borewit** [comment]
> oh looks like dependabot has re-used the label as it matches *dependency* but should prioritise an existing dependencies label.

That is indeed what it looks like, thanks.

**Comment by feelepxyz** [comment]
@Borewit sorry for dropping this, you can work around this by setting your default labels to something specific: https://dependabot.com/docs/config-file/#default_labels

This will override the default behaviour where dependabot tries to find an existing label named `*dependenc*` and use that instead of creating a `dependencies` label. In your case it looks like this label also exists so we should be prioritising that over the regex match. Will look into fixing that but you can work around it by specifying `default_labels` using the config file.

**Comment by Borewit** [comment]
> @Borewit sorry for dropping this, you can work around this by setting your default labels to something

I am aware of the workaround, yet the current behavior is wrong.

**Comment by feelepxyz** [comment]
@Borewit I've shipped a fix for this to always pick an existing `dependencies` label if one exists, which should fix the issue for your repo, otherwise fall back to a label matching `/*dependenc./i`.
