### ISSUE TITLE
Missing changelog for libvirt (python)

### ISSUE THREAD

**Issue by canihavesomecoffee** [dependabot/feedback#883]
Libvirt as a python library does not contain a changelog, which makes it a bit harder to judge the upgrade process.

An example is https://github.com/CCExtractor/sample-platform/pull/365.

After a search I found the change log here:
- https://libvirt.org/news.html
- https://libvirt.org/git/?p=libvirt.git;a=blob;f=docs/news.xml;h=ae4ee444d0f6acd0c8e51122ceb36f1c914f55fa;hb=HEAD

Is there a way to update DependaBot to be able to include this changelog?

**Comment by jurre** [comment]
Hi @canihavesomecoffee, thanks for using dependabot!

It seems like this happens because libvirt has a `ChangeLog` file in the root of their project:

https://libvirt.org/git/?p=libvirt.git;a=blob;f=ChangeLog;h=55eb05c5ce338b34f530e09a2b2752d1262c5507;hb=HEAD

However, this merely states:

```
libvirt ChangeLog
=================

The libvirt project doesn't include a detailed ChangeLog in its release
archives.

If you're interested in the full list of changes made to libvirt since
the project was started, you can clone the git repository from

  https://libvirt.org/git/libvirt.git

and browse them locally using your favorite git history viewer or,
alternatively, browse them online at

  https://libvirt.org/git/?p=libvirt.git;a=log
```

When dependabot searches for the changelog it checks the root directory of a project for these files: `changelog news changes history release whatsnew` and does a diff on the new vs old version, which in this case won't have changed.

It would be pretty hard for us to support grabbing the changes from the `docs/news.xml` file in a generic way.

I would suggest asking the maintainer to start using the ChangeLog file as it's pretty common practice, and it seems that they are already writing the changelog currently.

**Comment by canihavesomecoffee** [comment]
Thank you for the quick reply & explanation.

I'll then get in touch with the developers and see if it's possible to get this working :)

I'll close this issue then for now as it's more something they can do rather than what DependaBot should do.
