### ISSUE TITLE
Allow JavaScript projects without a lockfile

### ISSUE THREAD

**Issue by nblackburn** [dependabot/feedback#9]
As it stands, Yarn is required but i feel it should be optional just as yarn is.

**Comment by greysteil** [comment]
Hey @nblackburn, we'd love to build out JS support further. Next on the list there is supporting npm5 - are you suggesting also supporting projects without a shrinkwrap / lockfile?

**Comment by nblackburn** [comment]
@greysteil yes, while i agree with the purposes of lockfiles i still consider flexibility to be important enough to allow for both.

**Comment by greysteil** [comment]
We've just announced [support for npm](https://dependabot.com/blog/dependabot-now-supports-npm), so I'm renaming this to focus on supporting JS projects without a lockfile.

**Comment by greysteil** [comment]
This is now live, although slightly in stealth mode. If you try adding a repo without a `package-lock.json` when specifying the language `JavaScript (npm)` then everything should just work. 🎉 

I'm going to tidy up Yarn support so it does the same and then blog about it.

**Comment by styfle** [comment]
@greysteil I'm curious, what are the pros/cons of using dependabot with a lockfile? I'm a little surprised that it was only working with lockfiles up until now.

**Comment by simondel** [comment]
@greysteil Awesome! It works 🥇 
![image](https://user-images.githubusercontent.com/4221997/33524102-836fa152-d816-11e7-8fed-b12b02afb3a1.png)

Is there a way to increase the maximum amount of languages (or in my case packages) in a single project?

**Comment by greysteil** [comment]
🎉 

@simondel - I don't think there's a limit to the number of packages you can add to a single project, but the above does look a bit impractical! I'll have a look at adding proper Lerna support soon.

@styfle - Dependabot was originally built to work with applications, rather than libraries, where the benefits of having a lockfile are pretty well written about (basically a full deterministic environment). In the JS community it looks like a lot of people commit their `yarn.lock` or `package-lock.json` when working on a library, too, so Dependabot is already running on quite a few JS libraries, but allowing Dependabot to work without a lockfile should mean it can support more.

I'd love both of your thoughts on what the right behaviour for Dependabot is when updating repos without a lockfile. Currently it will make updates like `^1.0.0` -> `^1.7.0`, but I'm not sure that's desirable - would it be better to leave requirements like that alone and only make updates like `^1.0.0` -> `>=1.0.0 <3.0.0`? That's what we do in Ruby.

**Comment by simondel** [comment]
@greysteil well, the 'add language' button goes away when I specify 7 languages (you can see this on the screenshot as well)

**Comment by greysteil** [comment]
@simondel - oops! Deploying a fix for that now.

**Comment by simondel** [comment]
@greysteil Works like a charm, thanks!!
![image](https://user-images.githubusercontent.com/4221997/33525976-a720cb94-d839-11e7-910a-13adbaedb586.png)

**Comment by nblackburn** [comment]
@greysteil Fantastic work, thanks for tackling this issue.
