### ISSUE TITLE
Feature Suggestion: add a report of the dependency map

### ISSUE THREAD

**Issue by haven-gr** [dependabot/feedback#94]
As Dependabot must inventory all the dependencies, let users take advantage by offering a map of the dependency tree

**Comment by greysteil** [comment]
I'm totally 👍 on this. Planning to add a show view for repos / update configs soon which will let you see your dependencies, any that Dependabot is ignoring (on request) etc.

Cc @petehamilton.

**Comment by james-w** [comment]
A report of what dependabot sees, and why it is/isn't acting on something would be great. I'm currently trying to figure out why it isn't sending us a PR for one dependency, and having somewhere to look for that would be so much better, as well as having an overall view of the health of our dependencies, rather than trying to infer it from how many PRs we are getting.

**Comment by greysteil** [comment]
I'm going to close this because now we're owned by GitHub this will certainly be an extension of the Dependency Insights screen GitHub offers.

@james-w we'd love to do that but it's a *lot* of work. In the meantime, check out [Dependabot Script](https://github.com/dependabot/dependabot-script), which is the best way to replicate what's going on in Dependabot's logic.
