### ISSUE TITLE
Ruby: pre release gems

### ISSUE THREAD

**Issue by ferrarimarco** [dependabot/feedback#95]
Hi!

I added a project on dependabot: https://github.com/ferrarimarco/docker-github-changelog-generator

Dependabot watches the Dockerfile and the Gemfile for updates.

Here are the contents of the Gemfile:

```
source 'https://rubygems.org' do
  gem 'github_changelog_generator', '1.14.3'
end
```

For the github_changelog_generator gem there are three new pre-release versions, as you can see from https://rubygems.org/gems/github_changelog_generator

Why is Dependabot not proposing PRs for these versions? Are pre-release versions ignored? Is there some documentation that details this?

Thanks!

PS: already tried to bump manually and to remove and readd ruby as a watched language for that project.

**Comment by greysteil** [comment]
Hey @ferrarimarco 👋.

Dependabot won't propose updates from a non-pre-release version to a pre-release version, but it *will* update you between pre-release versions.

For your repo, since you don't have a `Gemfile.lock` committed, Dependabot is looking at the Gemfile and seeing that it doesn't currently want pres (because the version in the requirement isn't a pre). As a result, it's not trying to update you. If you were to use an old pre-release version in there, like `1.15.0.pre.alpha`, then Dependabot would generate an update PR for you.

**Comment by ferrarimarco** [comment]
@greysteil I don't know if it's related but it's not bumping bundler.

Here is my Gemfile:

```
source 'https://rubygems.org' do
  gem 'bundler', '1.16.2'
  gem 'github_changelog_generator', '1.15.0.pre.rc'
end
```

Bundler is at 1.16.3: https://rubygems.org/gems/bundler

**Comment by greysteil** [comment]
Huh, that’s weird. Bundler’s handling of itself is slightly different to other gems - it never locks itself in the Gemfile.lock. That shouldn’t be stopping it from updating the Gemfile requirements, though - I’ll take a look.

**Comment by ferrarimarco** [comment]
Here is what I'm doing:

1. Put bundler version in Gemfile
1. Fetch this version in the Dockerfile: `gem install bundler --version $(cat Gemfile | grep bundler | awk -F "'" '{print $4}')`

With this trick I keep not only the gems but also bundler updated as Dependabot should take care of that as well.

**Comment by greysteil** [comment]
Good spot - turns out that Dependabot wasn't updating `bundler` in your repo because of a weird edge case. Because it was wrapped in a source blog, Dependabot was tapping into Bundler itself to ask it to fetch its latest version. There's a special case in the current version of Bundler that in the Bundler codebase [here](https://github.com/bundler/bundler/blob/1e3c630d3f968c9b4c9b8996b940be4694d58544/lib/bundler/fetcher.rb#L136), so Dependabot wasn't getting an updated version for it.

I've fixed that in [this commit](https://github.com/dependabot/dependabot-core/commit/6eb7e60f8501c2ab611a595b0097bb8fca3af227) and added tests so it won't regress.

Thanks for the feedback!
