### ISSUE TITLE
Process to whitelist dependencies should be language specific

### ISSUE THREAD

**Issue by matthewmcgarvey** [dependabot/feedback#96]
The only option, currently, is to fill in a comma separated list.  This might work for ruby where dependencies are only one word like rails, or puma, but this doesn't work for every language.  Maven, for example (and java in general because they follow maven's naming scheme), separates dependencies into a two part naming scheme, a group id and an artifact id and there is no clear instruction for what that format looks like and it makes me doubt that feature even works for languages like java.  I think the form should be more than a text field.

**Comment by greysteil** [comment]
Ah, good point. It will work for Maven, but you'd need to downcase the name and link the group id and artefact id with a colon.

I totally agree on making this a select, or something like that, rather than plan text. I'll add it to the roadmap, and in the meantime will change the help text on that field.

**Comment by greysteil** [comment]
The following update is deploying now:

![image](https://user-images.githubusercontent.com/1144873/42903482-f5a94a70-8a9f-11e8-8178-a793938b69cc.png)

Thanks for the feedback!

**Comment by feelepxyz** [comment]
@matthewmcgarvey we've just added a dropdown with available dependencies to the whitelist 🎉
